### ISSUE TITLE
parseDate does not parse string from date.toJSON or date.toISOString

### ISSUE THREAD

**Issue by twalker** [jquery/globalize#117]
This may be more of a feature request.
I think Globalize.parseDate should support the output from ES5 Date methods, toJSON and toISOString, regardless of culture.

```javascript
var date = new Date();

Globalize.parseDate(date.toISOString());
// returns null
Globalize.parseDate(date.toJSON());
// returns null
```
An [approach I took](https://github.com/twalker/globalize/commit/4e9c4d503926f45b7ea6f71a91cd3f9e3645066d) to support this was to give the native Date parser a chance to parse the string.

I've added this approach to [my existing pull request](https://github.com/jquery/globalize/pull/106).
Please consider pulling my changes.

**Comment by rxaviers** [comment]
One could parse such string using native JaveScript Date. Not necessarily via Globalize. Anyway, it's possible to use `raw` option to get `parseDate` on Globalize 1.x to parse ISO strings if for some reason it's desired.

Feel free to add new comments on any problems. Thx for raising this issue. Sorry for the long delay for any answer.
