### ISSUE TITLE
Integers glitch after reaching a specific length

### ISSUE THREAD

**Issue by Jshauk** [jquery/globalize#167]
I tried typing a number in that is longer than 18 digits, it replaces all the numbers at the end with 0
I believe the problems lies within the highlighted code
![code](https://f.cloud.github.com/assets/4127145/638495/af57de28-d2bd-11e2-9553-9c2a240d688e.png)
Example:
![error-example](https://f.cloud.github.com/assets/4127145/638548/2ad670b8-d2bf-11e2-9e6c-2e8c9682f7ea.png)

**Comment by rxaviers** [comment]
This seems a very hard problem. I'm closing as won't fix. But, I am open for ideas and code suggestions.

**Comment by SlexAxton** [comment]
There is `Number.MAX_SAFE_INTEGER` now

**Comment by rxaviers** [comment]
Thanks for the input
