### ISSUE TITLE
Hijri Calendar

### ISSUE THREAD

**Issue by ammarabdulsalam** [jquery/globalize#175]
Hello, when changing calendar to Hijri using:
Globalize.culture("ar-SA").calendar = Globalize.cultures["ar-SA"].calendars.Hijri;
it appears to be changed and:
console.log(Globalize.culture().calendar.name)
returns the right name
but the date appears wrong because it shows 31 day while it should place 30 or 29, and the months and the dates appear wrong, I mean it doesn't select the right month.

Regards,

**Comment by rxaviers** [comment]
Globalize 1.x doesn't support Hijri calendar (regression). If you need such support, please weigh in #320. I'm closing this issue in favor of that to help focus our efforts. Also, note the new implementation is going CLDR, therefore different data.
