### ISSUE TITLE
Plans on ordinals

### ISSUE THREAD

**Issue by rikkertkoppes** [jquery/globalize#193]
Any plans on ordinals (1st, 2nd, 3rd, 4th etc)?

I may give it a go, but I'd reckon to wait for the cldr bit?

**Comment by jzaefferer** [comment]
I've read all the comments here just now and I'm still not sure for ordinals and cardinals really are. It would help to replace this ticket with one that outlines a potential API, along with unanswered questions and references. That would make it much easier for interested parties to contribute an implementation.

**Comment by rxaviers** [comment]
I agree. Replaced by #403
