### ISSUE TITLE
incorrect parsing using the Japanese calendar

### ISSUE THREAD

**Issue by blq** [jquery/globalize#22]
trying to parse any of the date-formats using the ja-JP Japanese calendar seem to fail with a 100 year offset. Well, all but the last "1955" example.

// Fredrik Blomqvist

**Comment by rxaviers** [comment]
Globalize 1.x doesn't support Japanese calendar (regression). If you need such support, please weigh in #320. I'm closing this issue in favor of #320 to help focus our efforts. Also, note the new implementation is going to use CLDR data and potentially new code as well.
