### ISSUE TITLE
parsing using the Hijri calendar fails in "d" mode.

### ISSUE THREAD

**Issue by blq** [jquery/globalize#23]
parsing using the Hijri calendar fails in "d" mode.
ex "04/11/90" (Thu Dec 31 1970) => Sat Feb 17 2553

// Fredrik Blomqvist

**Comment by rxaviers** [comment]
Globalize 1.x doesn't support Hijri calendar (regression). If you need such support, please weigh in #320. I'm closing this issue in favor of #320 to help focus our efforts. Also, note the new implementation is going UTS#35 specs, therefore different patterns.
