### ISSUE TITLE
parsing using the UmAlQura calendar fails in "d" mode.

### ISSUE THREAD

**Issue by blq** [jquery/globalize#24]
parsing "d" dates using the UmAlQura calendar returns null dates.

// Fredrik Blomqvist

**Comment by rxaviers** [comment]
Globalize 1.x doesn't support UmAlQura calendar (regression). If you need such support, please weigh in #320. I'm closing this issue in favor of the latter to help focus our efforts. Also, note the new implementation is going to use UTS#35, therefore new patterns.
