### ISSUE TITLE
Support formatting units, eg. secs, days

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#252]
PR #254

Format units such as seconds, minutes, days, weeks, and everything else supported by CLDR.

**Requires**
- #220 Plural

**API**

.formatUnit( value, unit [, options] );

Examples:
```javascript
.formatUnit( 1, "month" ); // 1 month
.formatUnit( 5, "week" ); // 5 weeks
.formatUnit( 30, "day" ); // 30 days
.formatUnit( 30, "day", { form: "narrow" }); // 30d
```

Value: Number

Unit: String, eg. "month", "day", etc.

Options:

- form ("long"|"short"|"narrow") used when tense = null to specify the unit form, eg. ("2 seconds", "2 secs", or "2s").

**Specs**

- [TR35 Unit Elements](http://www.unicode.org/reports/tr35/tr35-35/tr35-general.html#Unit_Elements)

**CLDR**

Units can be found on [main/<lang>/units.json](http://www.unicode.org/repos/cldr-aux/json/25/main/en/units.json).

**Ecma proposal**

- https://github.com/tc39/ecma402/issues/32

--
Fore more background: see #391.

**Comment by arkihillel** [comment]
This is a must have as far as I'm concerned. Would be glad to help if needed. 
What I tried to do a week ago before realizing I couldn't with the current version of globalize might help you get a clear use case:

**Display week dates**
```javascript
function formatWeek(startDate, language) {
	var startDate = new Date(startDate);
	var i18nString = _('%s of %s to %s');
	var i18nWeek = Globalize.formatUnit( 1, "week" );
	var i18nFirstDay = Globalize.formatDate(startDate, {skeleton: 'yMd'});
	var i18nLastDay = Globalize.formatDate(startDate.setDate(startDate.getDate() + 6), language, {skeleton: 'yMd'});
	return util.format(i18nString, i18nWeek, i18nFirstDay, i18nLastDay);
}
```

**Comment by rxaviers** [comment]
It was not clear to me whether the API specified here (and partially implemented by #252) is sufficient for you? If it is, you can help me to finish #252, so we can land it. Right now, it misses functional tests and docs. It got stalled due to lack of time/resource to work on it.

**Comment by arkihillel** [comment]
#252 perfectly fits my needs. I'd be glad to help and will look into documenting it whenever I have free time.

**Comment by rxaviers** [comment]
Awesome, feel free to add comments needing help. As soon as we get those items tick, it should be good to land on master.

**Comment by rxaviers** [comment]
Ecma proposal
- https://github.com/tc39/ecma402/issues/32
