### ISSUE TITLE
Date (skeletons): handle date and time in the same skeleton

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#272]
Currently, it's possible to:

```
> Globalize.formatDate(new Date(), "MMMd")
'Jun 3'
> Globalize.formatDate(new Date(), "hms")
'1:40:31 PM'
```

Although, `.formatDate( date, "MMMdhm" )` isn't. But, it should.
http://www.unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems

> If a client-requested set of fields includes both date and time fields, and if the availableFormats data does not include a dateFormatItem whose skeleton matches the same set of fields, then the request should be handled as follows:

> 1. Divide the request into a date fields part and a time fields part
> 2. For each part, find the matching dateFormatItem
> 3. Combine the patterns for the two dateFormatItems using the appropriate dateTimeFormat pattern, determined as follows from the requested date fields:
>  - If the requested date fields include wide month (MMMM, LLLL) and weekday name of any length (e.g. E, EEEE, c, cccc), use <dateTimeFormatLength type="full">
>  - Otherwise, if the requested date fields include wide month, use <dateTimeFormatLength type="long">
>  - Otherwise, if the requested date fields include abbreviated month (MMM, LLL), use <dateTimeFormatLength type="medium">
>  - Otherwise use <dateTimeFormatLength type="short">

See also: https://github.com/ibm-js/ecma402/issues/76

**Comment by ManrajGrover** [comment]
@rxaviers sir,

I see [ibm-js/ecma402/issues/76](https://github.com/ibm-js/ecma402/issues/76) have already implemented `long` , `medium` , `short` which is already available here under preset `datetime` . If there is more customization like above examples given by you, what we can do is parse the skeleton and see date and time component and call formatDate for both separately and return accordingly. But yes there may be several cases we have to take care of. For example, `"GyMMM"` and similar skeletons: In this we would need to put `AD` after the time. Also it may be possible user asks for time first before date. So should take care of all flexibilities.

I would like to take this up if possible.

**Comment by rxaviers** [comment]
> is already available here under preset datetime

Yeap, this issue isn't about the presets. But, skeletons.

> For example, "GyMMM" and similar skeletons: In this we would need to put AD after the time. Also it may be possible user asks for time first before date. So should take care of all flexibilities.

@ManrajGrover note there's a difference between skeletons and raw patterns. A skeleton is mapped into a raw pattern. For example, `GyMMM` skeleton becomes `MMM y G` raw pattern for `en-US`, and `Gy年M月` raw pattern for `zh-CN`. So, note the order of the pattern-fields in a skeleton doesn't select their order in the final raw pattern. That's its beauty by the way. A skeleton should be always in the [canonical order](http://www.unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems).

> and call formatDate for both separately and return accordingly

I'm looking for a solution that extends [date/expand-pattern](https://github.com/jquery/globalize/blob/master/src/date/expand-pattern.js).

**Comment by ManrajGrover** [comment]
@rxaviers sir,

Ohkay sir. So basically the pattern should be entered in canonical form and then should be extracted and processed, right? The method mentioned in [this](http://www.unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems) can be used but it does not say anything about the time. What if user wants dates `"full"` date but `"short"` time? There this method will return `datetime: "full"` .

I would suggest we take each date and time separately and then concatenate them. One more thing is if either date nor time don't exist, should we throw an error or give a closest form of datetime? How to do that?

I went through the code given in [date/expand-pattern](https://github.com/jquery/globalize/blob/master/src/date/expand-pattern.js) and saw we can handle these in `case "skeleton" in pattern`.

**Comment by rxaviers** [comment]
> So basically the pattern should be entered in canonical form and then should be extracted and processed, right

Correct.

> What if user wants dates `"full"` date but `"short"` time? There this method will return `datetime: "full"` .
>
> I would suggest we take each date and time separately and then concatenate them. One more thing is if either date nor time don't exist, should we throw an error or give a closest form of datetime? How to do that?

We won't handle the combination of different values for date and time separately.

> I went through the code given in [date/expand-pattern](https://github.com/jquery/globalize/blob/master/src/date/expand-pattern.js) and saw we can handle these in `case "skeleton" in pattern`.

Just let me know in any questions.

**Comment by ManrajGrover** [comment]
@rxaviers sir,

We can check if it is date or time or datetime. 
```javascript
if(skeleton.isDate() || skeleton.isTime()){
    then do default search for result
else if(skeleton.isDateTime){
    then follow four if cases listed above.
}
```
Last case is default `short`. We won't be doing appendItems as mentioned in [this](http://www.unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems) link last paragraph, right?

I shall start working on it.

**Comment by rxaviers** [comment]
Yeap, your high level sketchup seems correct. Looking forward to it. Thanks

**Comment by ManrajGrover** [comment]
@rxaviers sir,

I have almost completed the feature. It is throwing error for the case containing `"MMMME"` and `"MMMM"` . This is because the CLDR does not contain these pattern. Though I just need to give `"full"` as result for them, which I am, it is throwing `"E_MISSING_CLDR: Missing required CLDR content `main/en/dates/timeZoneNames/gmtFormat`."` on line 84 in globalize.js .

**Comment by rxaviers** [comment]
> it is throwing `"E_MISSING_CLDR: Missing required CLDR content 'main/en/dates/timeZoneNames/gmtFormat'"`.

Have you loaded all [required CLDR data for the Date module](https://github.com/jquery/globalize/#2-cldr-content)?

**Comment by rxaviers** [comment]
> Though I just need to give `"full"` as result for them, 

Why do you need to return `full`?

> I have almost completed the feature. It is throwing error for the case containing `"MMMME"` and `"MMMM"` . This is because the CLDR does not contain these pattern.

I'm confused why are checking `"MMMM"` given it's about the month pattern only. It has nothing to do with handling date and time in the same skeleton.

Can you handle `"MMME"`? I'm mostly interested on handling date and time patterns in the same skeleton. Not #271.

**Comment by ManrajGrover** [comment]
@rxaviers sir,

According to the link, there are 4 cases, first one being when skeleton has `"MMMM"` and a day component. For that it says to print answer as `datetime: "full"`. Yes sir, similarly for next three cases, I am returning `"long"` , `"medium"` and `"short"`. `"MMME"` comes under Case 2.

**Comment by rxaviers** [comment]
It's not saying you should use `datetime: "full"` (this is a Globalize definition). But, `<dateTimeFormatLength type="long">`, which is the "glue" pattern from CLDR data.

**Comment by rxaviers** [comment]
I assume you have seen this data. But, just in case http://www.unicode.org/repos/cldr-aux/json/26/main/en/ca-gregorian.json

**Comment by ManrajGrover** [comment]
Yes sir. I have been following this only and have inferred the data from this and the link I mentioned before working. Sir, by "glue" pattern you mean?

**Comment by rxaviers** [comment]
"dateTimeFormats": {
              "full": "{1} 'at' {0}",
              "long": "{1} 'at' {0}",
              "medium": "{1}, {0}",
              "short": "{1}, {0}"
    }

**Comment by ManrajGrover** [comment]
Yeps. I have used them only. Should I send a PR? That will help clear things.

**Comment by rxaviers** [comment]
Great then. Yeap, please do so.
