### ISSUE TITLE
Docs: Add examples for dateFormatter with date and time formats

### ISSUE THREAD

**Issue by jzaefferer** [jquery/globalize#273]
There's really just one example for `formatDate`, which uses `datetime`. Would be good to have more examples.

Maybe also provide links or more docs to what the various formats actually mean, e.g. what does a medium time format look like. Currently there are no details nor references for that.

--
EDIT: https://github.com/jquery/globalize/blob/master/doc/api/date/format.md#example

**Comment by ManrajGrover** [comment]
@jzaefferer sir @rxaviers sir,

I would like to take this issue up. Please guide me. I feel one example each would be suffice. Any particular date and time to follow? Also should I follow the same pattern for documentation as for ``` dateFormatter() ``` ?

**Comment by rxaviers** [comment]
@jzaefferer this seems already implemented. What do you think of our current doc at https://github.com/jquery/globalize/blob/master/doc/api/date/date-formatter.md?

**Comment by rxaviers** [comment]
Should we add a similar table to the presetValues one demonstrating several skeletons?

**Comment by ManrajGrover** [comment]
Yes @rxaviers sir. I thought there was a need of giving code sample for each of ```date``` , ```time``` and ```skeleton```. 

Treating myself as a new user of library for the first time and want to use skeletons, I do feel there is need of more information for ```skeleton``` and samples. I think yes adding demonstrations of several skeletons to the documentation will fix this.

**Comment by jzaefferer** [comment]
Adding a similar table with examples for skeletons sounds good. Should mention the limited timezone support (see comment above or #202).

**Comment by rxaviers** [comment]
So, let's go for it. @ManrajGrover feel free to ping me on IRC needing any help.
