### ISSUE TITLE
parseFloat yields error on value undefined with jquery validate

### ISSUE THREAD

**Issue by dutompson** [jquery/globalize#306]
I'm using jQuery validate with Globalize 0.1.1 and there is function in validate sending the argument value as undefined. The situation I have is this: there is a group of radios, but none of them are selected, so the validate function if falling back to Globalize.parseFloat sending undefined as value.

The question is, should parseFloat accept undefined as value, or is it safe to patch the beginning of the function to return NaN if value is undefined, or null?

**Comment by rxaviers** [comment]
We should fix this. Closed in favor of #530, which states we should make the change consistent for all of our formatters and parsers.
