### ISSUE TITLE
Support for the Persian Jalali calendar

### ISSUE THREAD

**Issue by blq** [jquery/globalize#32]
Here's some pointers:
http://www.farsiweb.ir/wiki/Iranian_calendar
http://farhadi.ir/works/jalalijscalendar

Guess it should (at least) be added to the "fa-IR" and "*-AF" locales.

// Fredrik Blomqvist

**Comment by rxaviers** [comment]
If you need Persian calendar support, please weigh in #320. I'm closing this issue because new research might probably be needed given it's from 2011 and Globalize 1.x now follow UTS#35 and CLDR.
