### ISSUE TITLE
loadTranslations and Globalize.translate reverted to loadMessages and formatMessage in alpha14

### ISSUE THREAD

**Issue by joeybloggs** [jquery/globalize#377]
I recently updated to the latest globalize 1.0.0-alpha.14 and noticed that Globalize.loadTranslations() and Globalize.translate() are no longer present and have been changed in the documentation as well.

It seem that it somehow has been reverted to the old Globalize.loadMessages() and Globalize.formatMessage() which I have verified as working.

was this by accident or are the loadMessages and formatMessage replacing the loadTranslations and translate?

I much prefer loadTranslations and translate as it is much clearer on their function.

**Comment by rxaviers** [comment]
Hi @joeybloggs,

We now support MessageFormat (as in [ICU][]), which is a richer solution compared to what we had. So, the rename was to make it evident. Examples can be seen [here](https://github.com/jquery/globalize/blob/master/doc/api/message/load-messages.md#example) (note it's compatible with the former simple messages previously called translations).

Thank you for your observation and feel free to add more comments in any question.
[ICU]: http://site.icu-project.org/

**Comment by joeybloggs** [comment]
Thanks you for the quick response. I shall update my application.
