### ISSUE TITLE
Round off a decimal to integer format

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#379]
PR #415

Ref: https://github.com/jquery/globalize/issues/190#issuecomment-69546329

Whole numbers are not rounded.

**Comment by quentindemetz** [comment]
Not sure this is aptly named, as 100.7 is not a whole number...

**Comment by rxaviers** [comment]
Suggestion?

**Comment by arvind-kalyan** [comment]
Hi, Can I try this? The title could be : "Rounding off decimals to nearest integer"

**Comment by rxaviers** [comment]
Update the title accordingly. Just note that not necessarily it uses the "nearest", but `options.round`.

**Comment by rxaviers** [comment]
Please, feel free to. If you need any help just let me know. When you're ready, please send a PR.

**Comment by arvind-kalyan** [comment]
Sure. Thanks. Kindly check #globalize on IRC. I had sent a msg there few mins back.
