### ISSUE TITLE
Jon Skeet and the CLDR

### ISSUE THREAD

**Issue by johnnyreilly** [jquery/globalize#380]
This is not an issue - so please close it.  But I thought you might find this video by Jon Skeet talking about the CLDR interesting:

http://www.ndcvideos.com/#/app/video/2341

Gave me a whole new appreciation about the problem of internationalisation :smile:

**Comment by rxaviers** [comment]
Thanks for sharing. I18n is huge. The more you learn, the more you note there are to learn. So, it's important to converge efforts. We're always open to contributions. :smiley: (feel free to ping on IRC, Freenode @ #jqueryui-dev channel).
