### ISSUE TITLE
Remove dates from copyright notice

### ISSUE THREAD

**Issue by agcolom** [jquery/globalize#385]
These are some files I believe would be affected:
* [ ] https://github.com/jquery/globalize/blob/master/LICENSE.txt

* [ ] https://github.com/jquery/globalize/blob/master/src/build/intro-core.js
* [ ] https://github.com/jquery/globalize/blob/master/src/build/intro-date.js
* [ ] https://github.com/jquery/globalize/blob/master/src/build/intro-message.js
* [ ] https://github.com/jquery/globalize/blob/master/src/build/intro-number.js
* [ ] https://github.com/jquery/globalize/blob/master/src/build/intro-plural.js
* [ ] https://github.com/jquery/globalize/blob/master/src/build/node-main.js

There may be more...

**Comment by rxaviers** [comment]
- [ ] src/build/intro-currency.js

But, yeap this is it.

**Comment by rxaviers** [comment]
Also remove "Inc."  according to https://github.com/jquery/jquery/commit/66e1b6b8d49812239b5712d65922ff94c60f7b02.
