### ISSUE TITLE
user timezone

### ISSUE THREAD

**Issue by martingg88** [jquery/globalize#387]
is there any way to parse the utc date to user's preferred timezone?

besides that, i found out globalize.parseDate( "1/2/13", defaults) always return null value

**Comment by rxaviers** [comment]
> is there any way to parse the utc date to user's preferred timezone?

Please, could you explain this in a little more details? Do you want to parse or format?

> besides that, i found out globalize.parseDate( "1/2/13", defaults) always return null value

What's the output that you get when you `globalize.formatDate( new Date(), defaults )`? Basically, I need to know which locale you're using and what defaults means.

**Comment by martingg88** [comment]
1. I prefer to either parse or format given datetime to user local timezone. 
for example
change given datetime (Feb 02 2015 21:53:17 GMT+0800) to America/New_York (Feb 2, 2015 8:53 GMT-0500)

2. fyi...i'm using en-US locale. 
   globalize.formatDate( new Date(), defaults ) is working fine.
   However, globalize.parseDate( date string, defaults ) is always return null value

**Comment by rxaviers** [comment]
> 1. I prefer to either parse or format given datetime to user local timezone. 

The short answer is no, you cannot use Globalize to manipulate different timezones when parsing or formatting. But, yes you can use Globalize to format or parse dates using the user local timezone.

**Why not?** The native JavaScript Date object automatically sets the timezone offset based on the user's environment. This offset is used by Globalize when formatting or parsing. Given the fact Date doesn't allow one to set an arbitrary timezone, Globalize doesn't handle different timezones. More details can be found on https://github.com/jquery/globalize/pull/202 and https://github.com/jquery/globalize/issues/340.

**What you can do?** You can use the native Date object to parse an ISO String containing your input date (e.g., `new Date("1994-11-05T13:15:30-0100")`). Be aware of https://github.com/jquery/globalize/issues/181#issuecomment-48546595. Then you can use Globalize as usual to format such date instance.

> 2. fyi...i'm using en-US locale. 

What is `defaults` that you're referring to? The parsing works fine for me.

```
> Globalize( "en" ).formatDate( new Date(), {datetime: "full"})
'Sunday, February 15, 2015 at 7:06:51 PM GMT-02:00'
> Globalize( "en" ).parseDate( "Sunday, February 15, 2015 at 7:06:51 PM GMT-02:00", {datetime: "full"})
Sun Feb 15 2015 19:06:51 GMT-0200 (BRST)
```
