### ISSUE TITLE
Globalize.formatMessage alternative

### ISSUE THREAD

**Issue by michael-fischer** [jquery/globalize#388]
@rxaviers,

Is there any plans to have an alternative to formatMessage that will simply return the string from CLDR?  Consider the string, "There were {0} messages."  I would like to get that string back instead of the formatter which fails with a "Unable to get property '0' of undefined or null reference" since no additional arguments were passed to formatMessage.  

Thanks, Michael.

**Comment by rxaviers** [comment]
Hi @michael-fischer,

The problem I see with the method you're asking for is that it has no i18n value. All methods that are exposed by Globalize should address i18n needs in my opinion.

Having said that, I still want to understand your problem a little better. If you're not using Globalize to format messages, why are you loading them on Globalize? If all you need is a dictionary lookup, you can use straightforward JSON objects.

**Comment by michael-fischer** [comment]
@rxaviers I actually am using the I18N features of Globalize to provide the localization of the phrases.  The reason that I want to use Globalize to provide the strings is that this is replacing an ad-hoc solution that already has extensive custom code that handles the formatting aspects.  I was hoping to minimize the amount of changes necessary to get the framework in place.  Perhaps simply returning the message if arguments.Length = 1 would meet my needs.  It is certainly better than the unexpected exception that I got. :)

**Comment by jzaefferer** [comment]
Can you set "{0}" as the argument?

**Comment by michael-fischer** [comment]
@jzaefferer I'm not entirely sure what you are asking but if you are asking can I pass in the value.  For most.  For a few it will involve a lengthy refactor.  However, to me the question seems more about whether or not this should be a limitation of the framework?  That you can't return strings that are marked up that way.  Is there a reason the following change could not be made to message.js?

```javascript
	return function( variables ) {
		if ( typeof variables === "number" || typeof variables === "string" ) {
			variables = slice.call( arguments, 0 );
        }

        // can this check be added?
        if (variables === undefined || variables.length === 0) {
            return message;
        }

		validateParameterTypeMessageVariables( variables, "variables" );
		return formatter( variables );
	};
```

**Comment by rxaviers** [comment]
@michael-fischer yes, it's about passing the value in.

> Perhaps simply returning the message if arguments.Length = 1

Considering a message has placeholders (e.g. `{0}` or `{named}`), it's expected that those variables are passed in. If values are not passed in, there should be an error (perhaps a with a better error message) saying: "Missing value for placeholder {0}". This error cannot be bypassed.

**Comment by jzaefferer** [comment]
I'm not sure if my comment was clear, so let me clarify with an actual example:

```js
Globalize.formatMessage( path, [ "{0}" ] );
```

That should return the message at the given path with placeholder replaced with the same placeholder. That seems like a fair workaround given the constraints. You still need to know which paths are affected by this, but that should be less work than rewriting everything.

If that doesn't work, maybe you can switch to a different placeholder syntax? Then you could replace them after retrieving the message:

```js
Globalize.formatMessage( path ).replace( ... );
```

Anyway, based on what @rxaviers is saying, it seems like you need to find a workaround. I hope we can help you find one, until you can migrate to fully using the library as intended.

**Comment by rxaviers** [comment]
@jzaefferer, thanks for the clarification. I had understood it in a different way. Your suggestion seems a better workaround than what I had in mind.

**Comment by michael-fischer** [comment]
@jzaefferer that would probably be a good work around since both my thoughts didn't gain any traction.  It still encourage you to refactor Globalize to have a translateMessage method as well which could have the following code.

```javascript
	validateParameterPresence( path, "path" );
	validateParameterType( path, "path", typeof path === "string" || Array.isArray( path ),
		"a String nor an Array" );

	path = alwaysArray( path );
	cldr = this.cldr;

	validateDefaultLocale( cldr );

	message = cldr.get( [ "globalize-messages/{languageId}" ].concat( path ) );
	validateMessagePresence( path, message );

	// If message is an Array, concatenate it.
	if ( Array.isArray( message ) ) {
		message = message.join( " " );
	}
	validateMessageType( path, message );
```

Especially since that is what existed prior to [Alpha 14] (https://github.com/jquery/globalize/issues/377).  This would give the best of both worlds.

**Comment by michael-fischer** [comment]
I put an [example](https://gist.github.com/michael-fischer/3624aa2894a8e2f9e5fe) message.js in gist if you want to take a look.

**Comment by rxaviers** [comment]
@michael-fischer, the goal of the Message module is to provide the best solution that we believe for the realm of message formatting. The `.numberFormatter()` method addresses that problem by providing ICU message format support. Although the additional `.translateMessage()` may help in your particular case, it doesn't add value for the general users. Given you migrate your code, the suggested method is going to be useless for you as well.

I'm sorry that you have to rewrite some of your code. But, I encourage you to do so and take the benefit of ICU message format; or to work around it (either with @jzaefferer's proposal, or by using `cldr.get()` directly).

If you find any problems or you are unable to perform any message formatting with `.numberFormatter()` just let us know.
