### ISSUE TITLE
Runtime code (smaller and quicker) for production

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#398]
PR #436

**Goal**

On client side, performance is also about how fast our page loads. So, size matters. How to get the smallest/leanest bundle for production?

Suppose we need a plural function for English. That is what we need: a function that given a number, outputs the plural form. But, in order to get that, we need the English plural rules (from CLDR) and the library code to parse that rules in order to generate this simple function `function( count ) { return count == 1 ? "one" : "other"; }`. In the end, this tiny thing is what matters. What if we could precompile that at build time and deploy only this tiny function.

Our goal is to allow our formatters/parsers to output the precompiled function. So, by managing that at build time, we can remove the need for most of the library at runtime.

**General ideas**

- All formatters/parsers should expose a `.toString()` function to output itself as a clean string representation. Below, I'm referring to this function as runtime-formatters/runtime-parsers.
- runtime-formatters/runtime-parsers should not depend on CLDR data. But, it should depend on pre-processed properties only.
- runtime-formatters/runtime-parsers can reference other functions. Those functions should be packed and distributed as the runtime library for each module. For example, `globalize/date.runtime.js`, `globalize/number.runtime.js`, etc.

**References**
- http://handlebarsjs.com/
- [messageformat.js](https://github.com/SlexAxton/messageformat.js/blob/722ebabd4d64adb61025d45aa87c5c6a438e63f3/README.md#build-time-compilation)

**Comment by jzaefferer** [comment]
Handlebars also does this pretty well, providing a separate runtime to load with compiled templates. In combination with more-or-less simple requirejs plugins, the whole things can be automated pretty well.

**Comment by rxaviers** [comment]
Yeap, handlebars is actually the original motivator for messageformat.js as well. I've included its link as another reference. Thanks

**Comment by srk12345** [comment]
hi i'm shahrukh ur idea is good and sounding.Plz tell me how can i contribute in ur project.

**Comment by rxaviers** [comment]
Hi @srk12345, thanks for your interest on contributing to Globalize. A good initial reading is https://github.com/jquery/globalize/blob/master/CONTRIBUTING.md. Then, get yourself familiarized with the contributing workflow by fixing simpler issues, e.g., #393. Then, get familiarized with our source code. If you have any question just let us know.

**Comment by srk12345** [comment]
how can i start my work on plural function for english

**Comment by rxaviers** [comment]
I don't know what you're talking about. This is not about plural function for English. Note I've used a simplified compiled plural function for English in the description as an example of output.

**Comment by srk12345** [comment]
i have understood

**Comment by rxaviers** [comment]
@unindented as a follow up of https://github.com/SlexAxton/messageformat.js/issues/112, I'd like to let you know of https://github.com/rxaviers/yarsk/tree/react-globalize. It's react.js specific. But, it's a demonstration on how to use Globalize with webpack (using the work-in-progress runtime implementation being made here). When all this is landed, I hope to have generic Globalize examples to provide. I hope it helps for now.

**Comment by unindented** [comment]
@rxaviers This is so good. I'm even using React, so this will be heaven-sent.

Do you have an estimated date when this will be released to npm?

**Comment by rxaviers** [comment]
Awesome! I expect to have peer review on all those pieces (webpack plugins, react-globalize, and this runtime branch). It's hard to estimate a date, but the sooner as time permits :). Your feedback is welcome.

**Comment by unindented** [comment]
I'll try to find some time this weekend to really look into it, so that I can provide meaningful feedback.

**Comment by rxaviers** [comment]
For who is interested on the implementation of this issue, #436 is ready for review.
