### ISSUE TITLE
Could you include the minified versions in dist and build?

### ISSUE THREAD

**Issue by mbirtwell** [jquery/globalize#401]
I noticed that the minified version of the distributable files are generated by grunt but stored in a ./tmp directory rather than ./dist and not included in the build. I could quite easily make a pull request to change this but it looks like someone has intentionally chosen to do this so was wondering why?

This also applies to https://github.com/rxaviers/cldrjs

**Comment by rxaviers** [comment]
Not including the minified files (in here and in cldrjs) has been a design choice #348.

I also believe that by not including the minified files, applications are encouraged to do the right thing: bundle+minify their applications as a whole.
