### ISSUE TITLE
Support ordinals

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#403]
Support plural type: ordinals.

**API**

```js
Globalize.pluralGenerator([ options ]);
```

Options:
- type (String) accepts "ordinal" or "cardinal" (the default).

**References**

- http://www.unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules

**Comment by quentindemetz** [comment]
Hi @rxaviers, I'm happy to see the great work done here. Is it currently possible to do the following with globalize ?
```
Globalize.foobar(options)(2) -> '2nd'
```

Thanks

**Comment by rxaviers** [comment]
Thanks @quentindemetz, you can:

```js
Globalize('en').plural(2, {type: 'ordinal'})
// > 'two'

// OR

Globalize.loadMessages({
  en: {
    foo: "{ordinal, select, one {The 1st train} two {The 2nd train} three {The 3rd train} other {The {n}th train}}"
  }
});
Globalize('en').formatMessage('foo', {
  n: 2,
  ordinal: Globalize('en').plural(2, {type: 'ordinal'})
});
// > 'The 2nd train'
```

More details on:
- https://github.com/jquery/globalize/blob/master/doc/api/plural/plural-generator.md
- https://github.com/jquery/globalize/blob/master/doc/api/message/message-formatter.md

**Comment by quentindemetz** [comment]
Awesome, thanks !

**Comment by andreialecu** [comment]
@rxaviers There is a subtle bug in the example you pasted, I'm just posting this in case someone just copy pastes it.

The ICU message should be defined as:
```
foo: "{ordinal, select, one {The {n}st train} two {The {n}nd train} three {The {n}rd train} other {The {n}th train}}"
```

Otherwise passing any number that ends with digit 1, 2 and 3 will be replaced with 1st, 2nd and 3rd. (eg, passing `21` will return `The 1st train`)

**Comment by rxaviers** [comment]
Thank you @andreialecu, would you like to include this example in our docs at https://github.com/jquery/globalize/blob/master/doc/api/message/message-formatter.md#plural-inflections?
