### ISSUE TITLE
Suggestion: Simpler loading of CLDR with loadFromPath() and fix leaking internal path information

### ISSUE THREAD

**Issue by hannes-landeholm** [jquery/globalize#405]
I don't understand why people writing applications that use globalize.js have to bother with the internal path standard that CLDR uses and understand what module uses what paths? Unless I'm mistaken, in 99% of all cases users will just put the CLDR data somewhere and then use globalize.js without changing any paths.

* It's a headache for web developers as they have to read documentation about CLDR and the "getting started guide" instead of just plugging in globalize.js and the CLDR data and using it.
* It leaks information to a layer that shouldn't even ideally have access to the information. What CLDR data certain globalize.js modules use is not relevant for applications using globalize.js and they should not define them at all.
* It cements the CLDR path standard so if it ever changes in the future I have to rewrite my application with new paths instead of just updating globalize.js and my CLDR json mirror.

Instead of doing this insanity: 

    $.when(
      $.get( "/static/cldr/main/en/ca-gregorian.json" ),
      $.get( "/static/cldr/supplemental/likelySubtags.json" ),
      $.get( "/static/cldr/supplemental/timeData.json" ),
      $.get( "/static/cldr/supplemental/weekData.json" )
    ).then(function() {
    
      // Normalize $.get results, we only need the JSON, not the request statuses.
      return [].slice.apply( arguments, [ 0 ] ).map(function( result ) {
          return result[ 0 ];
      });
    
    }).then( Globalize.load ).then(function() {
    
      // Your code goes here.
    
    });

Why not just simply provide this interface which does all those things itself instead?

    Globalize.loadFromPath("/static/cldr/", ["en"], ["date"], function(success) {
        // Your code goes here.
    });

* More future proof.
* Much easier and simpler to use.

In addition, I think the README should be updated so this way is strongly recommended and any other method is hidden in some "advanced use" section. The table describing what modules uses what CLDR data should be removed or hidden.

Thank you.

**Comment by rxaviers** [comment]
Hi, your feedback is very much appreciated.

As far as I understood your suggestion, `Globalize.loadFromPath()` should perform I/O. How do you want to handle the various different environments (couple of [examples here](https://github.com/jquery/globalize/blob/master/doc/cldr.md))? How many different environments there are? For browsers, should ajax be supported, jsonp, cors? If a user wants do load CLDR data from a CDN, how do we handle that? Potentially, jQuery would be included as a dependency, which doesn't make sense for Node.js users. Should we handle all the different ways of loading files? If a new scenario emerges, should we embrace that as well? What about users that want to [optimize their browser code for production](https://github.com/jquery/globalize/issues/398)? I believe this is a very large problem by its own and it doesn't belong to the i18n library realm.

Having said that, I am open to all ideas that help easing the content loading ramp up. For example, #345.

How can we get to the level of abstraction you are proposing, but without overloading Globalize? As a plug-in library?

**Comment by scottgonzalez** [comment]
Building tooling around CLDR to make managing the files easier shouldn't be that complicated. I believe @rxaviers even planned to do some work on that with https://github.com/rxaviers/cldr-data-npm or perhaps some additional tooling built on top of it. But I don't think Globalize should be concerned with making Ajax requests or accessing the file system.

**Comment by hannes-landeholm** [comment]
Yes, I did not intend to suggest that Globalize should do I/O directly. I should have been more clear on that.

BTW, the more I think about this the more I feel like it's an issue that should be fixed in cldrjs and not Globalize.js. I'm currently working on a pull request to https://github.com/rxaviers/cldrjs.

**Comment by rxaviers** [comment]
Ok, closing this and looking forward to hearing your ideas. I suggest to discuss your high level idea first. It might save time.

**Comment by hannes-landeholm** [comment]
I thought about building lazy loading in cldr.js but realised it's impossible because you need callbacks everywhere in Javascript and would literally need to break all the interfaces. So never mind, this is a Globalize issue after all.

**Comment by rxaviers** [comment]
If you have any updates after considering what Scott and I have said feel free to add comments in here.
