### ISSUE TITLE
Expose supplemental CLDR data

### ISSUE THREAD

**Issue by KL-7** [jquery/globalize#407]
It'd be nice to have things such as [currency symobls](http://www.unicode.org/repos/cldr-aux/json/25/main/es/currencies.json), [phone codes](http://www.unicode.org/repos/cldr-aux/json/25/supplemental/telephoneCodeData.json), and probably some other supplemental CLDR data exposed by globalize.js. 

It can be as simple as a thin wrapper class that provides an API for retrieving, e.g., currency symbols and phone codes based on a country code. Just to give you an idea, [here's](https://github.com/twitter/twitter-cldr-js/tree/master/lib/twitter_cldr/js/mustache/shared) how we expose this data in twitter-cldr-js (and the specs are over [here](https://github.com/twitter/twitter-cldr-js/tree/master/spec/js/shared)).

**Comment by rxaviers** [comment]
For comparison, follow below how cldrjs could be used to retrieve that.

```js
cldr = new cldr( "en-US" );

/**
 * Postal codes
 */

cldr.supplemental( "postalCodeData/{region}" ); // "\\d{5}([ \\-]\\d{4})?"

/**
 * Phone codes
 */

cldr.supplemental( "telephoneCodeData/{region}" ); // [{ "telephoneCountryCode": "1" }]

/**
 * Currency 3-letter ISO code
 */

cldr.supplemental( "currencyData/region/{region}" );
// [{
//   "USN": {
//     "_tender": "false"
//   }
// }, {
//   "USS": {
//     "_to": "2014-03-01",
//     "_tender": "false"
//   }
// }, {
//   "USD": {
//     "_from": "1792-01-01"
//   }
// }]
```

**Comment by mwmw7** [comment]
is there any API in Globalize.js for using "cldr-data/supplemntal/postalCodeData.json "

these day , i am testing globalize to use in our team project 

but i can find API for postal code

**Comment by rxaviers** [comment]
Hi @mwmw7,

Globalize uses a lower level library for Cldr traversing called [cldrjs](https://github.com/rxaviers/cldrjs). You can use it directly (see my example above).

Note, you can get the `cldr` instance from Globalize as well:

```js
// Static
Globalize.locale( "en" );
var cldr = Globalize.cldr;

// Instance
var globalize = new Globalize( "en" );
var cldr = globalize.cldr;
```

Did I answer your question? Just let me know if not.

**Comment by mwmw7** [comment]
So , 
cldr.supplemental("postalCodeData/{region}") returns  this -> \d{3}[\-]\d{3}  , when locale is ko

so i use this return value  for validation of postcode  

here is my snip code  
```javascript
 var postcode = '123-567';
 var postpattern = new RegExp(cldr.supplemental("postalCodeData/{region}"));
console.log(postpattern.test(postcode)); -> print true
```

**Comment by jzaefferer** [comment]
That looks simple enough. The only way to make this "easier" were to add a validation method to Globalize, like this:

```js
Globalize.validate("postalCodeData/{region}", "123-567")
```

That would retrieve the cldr property, wrap it in a RegExp and return the `test()` result. Not a big difference, and also less flexible - maybe you want to set flags on the RegExp?

**Comment by rxaviers** [comment]
@mwmw7, It seems very very correct to me. Here's the Unciode specs for it http://www.unicode.org/reports/tr35/tr35-info.html#Postal_Code_Validation.

**Comment by rxaviers** [comment]
@jzaefferer `"postalCodeData/{region}"` is an internal CLDR thing that I think user doesn't need to input. If we were to wrap that on Globalize, we could do something like `.validatePostalCode( "123-567" )`.

**Comment by jzaefferer** [comment]
Right, that makes more sense. Are there other cldr properties with regular expressions like this? If this is a unique snowflake, adding a method seems fine. Otherwise we might end up with plenty of these validate methods...

**Comment by mwmw7** [comment]
@rxaviers  yes you are right 
is there any task for this -> .validatePostalCode( "123-567" )  issue? 
than i want to add this new  API in globalize.js

**Comment by jzaefferer** [comment]
Looks like there are no other properties like that. Let's add `validatePostalCode` then. @mwmw7 could you put together a PR for that?

**Comment by mwmw7** [comment]
@jzaefferer  ok i will do that but what is PR? ^^

**Comment by arthurvr** [comment]
@mwmw7 Pull request :)

**Comment by mwmw7** [comment]
@arthurvr  oh~~~^^ i get it thank you

**Comment by rxaviers** [comment]
@mwmw7, consider creating a new module, e.g., `src/postalcode.js`. Also consider making `.validatePostalCode()` an alias for `postalCodeValidator()` (analogous to plural and pluralGenerator https://github.com/jquery/globalize/blob/master/src/plural.js)

**Comment by rxaviers** [comment]
I'm assuming `cldrjs` solves this problem and I'm closing this issue. Feel free to post new comments in case anyone thinks this should be re-discussed.
