### ISSUE TITLE
Try  include globalize  and cldrjs cdn  on plain-javascript are not working?

### ISSUE THREAD

**Issue by hubply** [jquery/globalize#414]
I try to include plain-javascript exsample by using cdnjs by include script on header html  but on console is display 
                                  "Uncaught TypeError: undefined is not a function"
 on  line Globalize.load({...}) function 

What something wrong?

**Comment by jzaefferer** [comment]
It sounds like you're trying to use an old version of Globalize (0.x) with methods from 1.x. Try to use Globalize 1.x properly: https://github.com/jquery/globalize#getting-started

**Comment by rxaviers** [comment]
Feel free to add new comments in case you're still finding trouble.

**Comment by hubply** [comment]
thank you. Work done!
