### ISSUE TITLE
Gregorian calendar implementation

### ISSUE THREAD

**Issue by mwmw7** [jquery/globalize#419]
I read some issue from old issue #280 
Implementation of the Gregorian calendar still does not exist?
than i think we have to implement  it , i think it is very very basic feature.

**Comment by jzaefferer** [comment]
I'm pretty sure the gregorian calendar support exists. An old closed issue doesn't change that. If you're referring to this:

> It has no calendar implementation (and has never had AFIAK).

The issue is talking about a "calendar control", like a datepicker. That's something else...
