### ISSUE TITLE
Update grunt-jscs

### ISSUE THREAD

**Issue by jzaefferer** [jquery/globalize#421]
Currently using 0.7.1, latest is 1.5.0. The latter contains many more rules, which were also added to the jQuery preset. Should try a newer version and see how much it reports that can be fixed by hand.

**Comment by rxaviers** [comment]
:+1:

**Comment by hzoo** [comment]
The autofix feature (`-x`) should be released soon (0.12) which might help a lot with errors!

**Comment by jzaefferer** [comment]
Can use `requireSpacesInsideParentheses: null` to deal with the updated spacing rules, until migration is done.
