### ISSUE TITLE
Document how to run cross browser tests using browserstack 

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#432]
npm install -g browserstack-runner
    export BROWSERSTACK_USERNAME=<>
    export BROWSERSTACK_KEY=<>
    browserstack-runner

**Comment by jzaefferer** [comment]
You can also link to the usage docs of browserstack-runner, which mentions the env variables. For more than one-off runs, those exports should be added to the user's `.bash_profile` (or whatever it is on Windows).

**Comment by rxaviers** [comment]
Close in favor of #450
