### ISSUE TITLE
numberParser incorrect when no integer is included

### ISSUE THREAD

**Issue by Mottie** [jquery/globalize#443]
I set up [this demo](http://jsfiddle.net/Mottie/gf3nu9q6/) using only a partial set of data, so maybe I'm doing it wrong...

```js
Globalize.numberParser()('.44');
// result = 44 (no decimal point)
Globalize.numberParser()('0.44');
// result = .44
```

**Comment by rxaviers** [comment]
Thanks for pointing it out. `.numberParser()('.44')` should definitely not return `44`.
