### ISSUE TITLE
Issue with raw format

### ISSUE THREAD

**Issue by andrea-spotsoftware** [jquery/globalize#444]
Hi everyone, i'm migrating to last version of globalize, but i'm having an issue when trying to parse a date with a raw format.

In the previous Globalize version, I used to do:
Globalize.parseDate('20150503', 'yyyyMMdd')
and everything was working fine.

Now, i updated the function to get the same result:
Globalize.parseDate('20150503', { raw: 'yyyyMMdd' }) but it's returning null.

Maybe i'm missing something, but i can't find a way to parse a dateString specifying raw format.
Is it a library bug?

**Comment by andrea-spotsoftware** [comment]
I have the impression that there is a bug somewhere:

    Globalize.parseDate('14041988', {raw:'ddMMyyyy'})
    -> Thu Apr 14 1988 00:00:00 GMT+0200 (W. Europe Daylight Time)

    Globalize.parseDate('19880414', {raw:'yyyyMMdd'})
    -> null

**Comment by rxaviers** [comment]
The parser is actually correct. Although, it's an interesting case.

`yyyy` means full year with padding. It doesn't necessarily mean the year should be limited to four digits ([reference](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table)). Therefore, it consumes the whole `19880414` considering it as an year. The same applies to `y` and `yyy+`. Note the only exception is `yy` (two digits year). Therefore, if you use `Globalize.parseDate('1988-0414', {raw:'yyyy-MMdd'})`, it works fine. Does that work for you? Follow below a workaround for your use case.

```js
stringDate = '19880414';
date = Globalize.parseDate(stringDate.slice(0,4) + "-" + stringDate.slice(4), {raw:'yyyy-MMdd'})
// > Thu Apr 14 1988 00:00:00 GMT-0300 (BRT)
```

**Comment by andrea-spotsoftware** [comment]
I understand, thank you for explanation. 
However the workarund is working, thank you again!

**Comment by rxaviers** [comment]
:+1:
