### ISSUE TITLE
Unresolved feature for number module

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [jquery/globalize#449]
cldr/unresolved works perfectly for message module, but there is a problem with number module. It throws E_MISSING_BUNDLE inspite of using root data (which is loaded from main/root). How can I make number module work for unresoved data?

**Comment by rxaviers** [comment]
I assume this is working fine. On any problem, feel free to reopen or add more messages.

**Comment by nikolaybobrovskiy** [comment]
Problem was in bundle definition. I was expecting it to use 'en' bundle for locale 'en-XX' (where XX is really XX), but it tried to use 'en-XX' which is absent and bundle was set to null. And I noticed minLanguage was defined as 'en-XX' but I had expected 'en'.

**Comment by rxaviers** [comment]
Yeap, it will try `en-XX` first. Then, considering you have `cldr/unresolved` loaded, it will do locale inheritance, therefore try `en`, then try `root`.

`XA..XZ` are private use region subtags and you can use `en-XX` just fine. But, as you've already noticed, Globalize will look for the `en-XX` bundle. It correctly doesn't look for the `en` bundle first as it means `en-US` (http://www.unicode.org/reports/tr35/tr35-info.html#Default_Content). Globalize (via cldrjs) deduces the default content from likelySubtags information.

Just let me know if there's anything I can help with.
