### ISSUE TITLE
Globalize.parseNumber strips out letters I'm not sure it should

### ISSUE THREAD

**Issue by Tridus** [jquery/globalize#457]
Hi. I'm trying to migrate something up from Globalize 0.x to 1.0, and I'm getting some weird behavior with numbers. Specifically, parseFloat in 0.x would consider a value like "asdf12" to be NaN, which is what I'd expect.

1.0 is returning 12. It does the same for "asdf12asdf", but not "asdf12asdf12", which is considered NaN.

I think the offending code is around here, in number.js:

		// Is it a valid number?
		value = value.match( numberNumberRe );
		if ( !value ) {

			// Invalid number.
			return NaN;
		}

It strips off the prefix and suffix text, so what's left is 12, but never checks if the prefix and suffix make any kind of sense at all. At least that's what it looks like it's doing to me, I'm not an expert on Javascript at all. :)

Is this the expected behavior now? Thanks for looking into it. :)

**Comment by rxaviers** [comment]
Thanks for bringing this issue into our attention. This should be fixed when https://github.com/jquery/globalize/issues/353 is fixed. We'll parse numbers similarly to the way we parse Dates (lexical analysis, then parsing).

Closing in favor of #353.

**Comment by Tridus** [comment]
Awesome, thank you. :)
