### ISSUE TITLE
parseFloat too permissive, e.g. 4,0 taken as 40

### ISSUE THREAD

**Issue by yucca42** [jquery/globalize#46]
Globalize.parseFloat("4,0",10,"en") yields 40, which is unacceptable. It should either work the same way as the standard parseFloat, parsing a number at the start of its first parameter (yielding 4) or parse the entire attribute as a number, recognizing that it does not fit into the number patterns of the locale (yielding NaN). The latter is preferable, as it would help in detecting data errors (like input "4,0" when a number in the English locale is expected).

It is highly probable that input like 4,0 in English locale is data error. It is extremely improbable that the user really meant the number 40

Technically, parseFloat, upon encountering a group separator, should test that there is a correct number of digits after it, as defined by numberFormat.groupSizes.

Similar considerations apply to parseInt, of course.

**Comment by rxaviers** [comment]
This issue should be fixed by #353. I've added notes there to ensure this is tested. I'm closing this issue in favor of the latter to focus efforts. If this is a problem for you, your help is very much appreciated.
