### ISSUE TITLE
currrencyFormatter should default to currency for locale

### ISSUE THREAD

**Issue by dpolivy** [jquery/globalize#463]
As a nice convenience, `currencyFormatter()` should default to using the default currency for the current locale when no other currency parameter is specified.

In order to enable this, the default currency code (ISO 4217) would need to be determined from the cldr data. It should also be accessible on the globalize object (perhaps in `globalize.cldr.attributes`), once determined.

**Comment by rxaviers** [comment]
This is not an option for `currencyFormatter()` due to UTS#35 recommendations:

> Note: Currency values should never be interchanged without a known currency code. You never want the number 3.5 interpreted as $3.50 by one user and €3.50 by another. Locale data contains localization information for currencies, not a currency value for a country. A currency amount logically consists of a numeric value, plus an accompanying currency code (or equivalent). The currency code may be implicit in a protocol, such as where USD is implicit. But if the raw numeric value is transmitted without any context, then it has no definitive interpretation.

http://www.unicode.org/reports/tr35/tr35-numbers.html#Currencies

Having said that, I'm open for ideas on how Globalize could make it easier to navigate/use CLDR information about currencies per territory.
