### ISSUE TITLE
Documentation: style updates

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#471]
- [ ] Use `0.` for item lists.
- [ ] No hard breaks in prose (ref #369).
- ... more to come

**Comment by arthurvr** [comment]
Quick question: I have at all no idea about the long-term plans with the documentation here, but does this make much sense when many docs will move to sites (API site and globalizejs.com)?

Don't hard wrap markdown files seems like a logical thing too. That's what we prefer for all other markdown in the org at least.

Maybe we should hold this off till https://github.com/jquery/contribute.jquery.org/issues/75 finally happens.

**Comment by rxaviers** [comment]
> Quick question: I have at all no idea about the long-term plans with the documentation here, but does this make much sense when many docs will move to sites (API site and globalizejs.com)?

The answer highly depends on when the move will occur. Right now, looking for contribution on that front :P.

> Don't hard wrap markdown files seems like a logical thing too. That's what we prefer for all other markdown in the org at least.
> 
> Maybe we should hold this off till jquery/contribute.jquery.org#75 finally happens.

Absolutely. Thanks for the link. So, let's wait for that to draw the actions items here.

**Comment by sotojuan** [comment]
> Right now, looking for contribution on that front :P.

I'd love to help moving the documentation to a website, but I am not experienced/know how I'd do that. Would we use one of those documentation-generating services?

> Use 0. for item lists.

I could help with this. But do you mean starting lists at 0?

**Comment by rxaviers** [comment]
> I'd love to help moving the documentation to a website, but I am not experienced/know how I'd do that. Would we use one of those documentation-generating services?

@sotojuan, there is information at https://github.com/jquery/api.globalizejs.com/issues/1 and https://github.com/jquery/globalizejs.com/issues/1.

raphamorim has started to work on the latter. I think you both chat and could work together. Current work-in-progress is at https://github.com/jquery/api.globalizejs.com/pull/2.

> I could help with this. But do you mean starting lists at 0?

@sotojuan, before we begin any work here, I'd like the Content team to bless this work. @arthurvr, do you know what's the status on this? Has any standard been defined?

Thanks

**Comment by arthurvr** [comment]
> @arthurvr, do you know what's the status on this? Has any standard been defined?

There's an open PR out there waiting for updates. It's probably better to wait for that before we start changing these here.

**Comment by rxaviers** [comment]
There's no point keeping this issue opened while there's no actual style guide for documentation. Closing for now. Could be reopened later.
