### ISSUE TITLE
loadMessages with array merges new message with old one instead of replacing it

### ISSUE THREAD

**Issue by nkovacs** [jquery/globalize#473]
Jsfiddle: http://jsfiddle.net/nkovacs/4b8wLmvn/

The string (hello) is replaced, the array is merged instead.

**Comment by nkovacs** [comment]
I worked around this by going through the messages object and converting all arrays to strings before passing it to loadMessages.

**Comment by rxaviers** [comment]
Hi, thanks for filing this issue. Globalize uses [cldrjs]() under the hood for the loading operation. The problem has a very simple solution: please see https://github.com/rxaviers/cldrjs/issues/32 and feel free to submit a PR or add new comments with questions.

I'm keeping this bug opened until the above cldrjs bug gets fixed and we bump its version in here.

**Comment by nkovacs** [comment]
You could work around it in case cldrjs cannot fix it because it's expected behavior in other cases.

**Comment by rxaviers** [comment]
I maintain cldrjs and I am open to get that fixed upstream there. :D
