### ISSUE TITLE
amd required?

### ISSUE THREAD

**Issue by gregpettit** [jquery/globalize#476]
Admittedly, I'm not really doing AMD in my applications right now. I know, I'm behind the times. Be that as it may, I'm a bit confused about how to include globalize.js

I ran through the install guide, and it said to require the cldrjs files and THEN require the globalize files and their modules. The sample HTML does not show any sort of dependency loader (requireJS or whatever) anywhere on the page.

Yet when I fire up the page, I get an undefined error on "define" in line 1 of globalize.js

The globalize files are taken from the ```dist``` folder of branch 1.0.0

Do I need to have requireJS (or similar) on my page before including the files, contrary to the example markup provided?

**Comment by gregpettit** [comment]
Ugh. So, it's CLDR giving me the undefined. The globalize sample is still "incorrect" but only because it assumes the CLDR do not need AMD. It's not globalize's fault directly. I will see if I can find non-AMD CLDR javascript files.

**Comment by rxaviers** [comment]
Hi @gregpettit, a quick comment for now:
- AMD is not mandatory
- We're working to improve the examples in our documentation. But, have you looked into https://github.com/jquery/globalize/tree/master/examples/plain-javascript?

**Comment by gregpettit** [comment]
rxaviers, this is totally user error. I appreciate that link, though!

Speaking of user error, I resolved the problem... (and it was just me being stupid)... I was trying to include cldr source files as distribution files. I'm not accustomed to the convention of going to a tagged branch and grabbing files from a dist folder, but now I know better!

The next problem that I have encountered is a typeerror (undefined) on this line:

```var createError = Globalize._createError,```

However, I suspect it's user error again. Since I'm not using AMD, I thought I would be clever and concatenate and then minify the CLDR files followed by the globalization files, all into one new file called "globalize.js" within my application.

Since this is testing on the dev branch, it is not minified, but it IS concatenated. Will concatenating the separate files together into one file mess things up? When using AMD I see that it wants to go into particular subdirectories, but I wouldn't imagine that would apply if not using AMD.

**Comment by gregpettit** [comment]
...and once again I answered my own question. ;) The files need to be separate and found within that directory structure.

I will try minifying them as separate files (this test was just plain non-minified inclusion exactly per documenation, which shouldn't be a surprise when it works as described!), but it looks like there is currently no way to avoid the extra HTTP requests through concatenation. Is that a fair assumption?

**Comment by rxaviers** [comment]
Although you can concatenate the files yourself, I suggest using smarter build tools. By concatenating, you need to take into account the correct dependencies order and the fact that CLDR is a JSON data (not a JavaScript code).

Feel free to suggest changes on how we could improve the documentation. Thanks

**Comment by gregpettit** [comment]
rxaviers, it's just more user error. I apologize for wasting your time. I in fact am using smarter build tools and haven't even gotten to including the CLDR data yet. This is just concatenation of the JavaScript files. Below is the Grunt concat task. To supposedly avoid a few keystrokes, I copy/pasted the globalize line in order to add the modules. I typed right over top of the main globalize.js file, though, so although I KNOW I need globalize.js, I had typed right over top of it and didn't notice.

Today has felt like amateur hour over at Greg's desk. ;)

The failed task:

```
globalize: {
        src: [
          'lib/cldrjs/cldr.js',
          'lib/cldrjs/cldr/event.js',
          'lib/cldrjs/cldr/supplemental.js',
          'lib/cldrjs/cldr/unresolved.js',
          'lib/globalize/globalize/date.js',
          'lib/globalize/globalize/message.js',
          'lib/globalize/globalize/number.js',
          'lib/globalize/globalize/plural.js',
          'lib/globalize/globalize/relative-time.js'
          //'lib/globalize/globalize/currency.js'         
        ],
        dest: '<%= dirs.purgatory %>/js/globalize.js'
}
```

and the fixed:

globalize: {
        src: [
          'lib/cldrjs/cldr.js',
          'lib/cldrjs/cldr/event.js',
          'lib/cldrjs/cldr/supplemental.js',
          'lib/cldrjs/cldr/unresolved.js',
          'lib/globalize/globalize.js',
          'lib/globalize/globalize/date.js',
          'lib/globalize/globalize/message.js',
          'lib/globalize/globalize/number.js',
          'lib/globalize/globalize/plural.js',
          'lib/globalize/globalize/relative-time.js'
          //'lib/globalize/globalize/currency.js'         
        ],
        dest: '<%= dirs.purgatory %>/js/globalize.js'
}

So embarrassing. But, I'll own my mistakes in the hopes that they help someone else some day.

I don't think the documentation needs improving. If you're the kind of person like me who wants to build by concatenating from globalization's `dist` folder instead of building from source each time, the implied information is already all there. "Include *these* files, in *this* order" is already in the documentation.

**Comment by rxaviers** [comment]
No problem. Using Globalize should be easy, so it's important that we constantly improve the library or the docs to accomplish that.

By concatenating yourself, make sure you follow the order listed here https://github.com/jquery/globalize/blob/master/examples/plain-javascript/index.html#L34-L57 (your fixed example is slightly different).

If you have any further questions, feel free to ping on IRC http://irc.jquery.org/ #globalize channel.

**Comment by gregpettit** [comment]
Thanks rxaviers. I have fixed the order. I am now in CLDR hell. More annoying tickets to come.
