### ISSUE TITLE
+CLDR JSON files from <name> module -- what are these?

### ISSUE THREAD

**Issue by gregpettit** [jquery/globalize#477]
In the documentation for using CLDR, there's a handy chart showing which CLDR files are needed for globalize to function properly. For example, the entry for "Currency Module" shows the following list:

cldr/main/locale/currencies.json
cldr/supplemental/currencyData.json
+CLDR JSON files from number module
+CLDR JSON files from plural module for name style support

I do not understand what the last two entries mean. The "dist" folder only includes JavaScript files, not JSON files. The CLDR package(s) do not have a distinct "number module". Where can I find these last two files?

**Comment by rxaviers** [comment]
Hi @gregpettit,

+CLDR JSON files from *number module* means these two files:

| Module | Required CLDR JSON files |
|---|---|
| Number module | cldr/main/`locale`/numbers.json<br>cldr/supplemental/numberingSystems.json |

+CLDR JSON files from *plural module* for name style support means these two files (note one is optional):

| Module | Required CLDR JSON files |
|---|---|
| Plural module | cldr/supplemental/plurals.json (for cardinals)<br>cldr/supplemental/ordinals.json (for ordinals) |

Feel free to add new comments on any questions and to submit a PR with improved text if you think clarification is needed.
