### ISSUE TITLE
E_UNSUPPORTED with date skeleton: 'yMMMM'

### ISSUE THREAD

**Issue by dpolivy** [jquery/globalize#478]
I am trying to use a dateFormatter with the following options:
```
{
    skeleton: 'yMMMM'
}
```

With locale `en-US`, it throws the following error:
E_UNSUPPORTED: Unsupported {&quot;feature&quot;:&quot;year pattern &#x60;u&#x60;&quot;}.

It seems to be unhappy with the 4 M's; if I use any other number, then it works fine (but doesn't format it as desired). Based on the [date symbol table](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table), I would expect 4 M's to use the full month name. I'm trying to format a date as "Month Year", e.g. "September 2009" for en-us.

Is this user error, a bug, or a data issue?

**Comment by rxaviers** [comment]
The root feature of what you look for needs to finish getting implemented: #271 (PR #462). The original contributor seems to have stalled the implementation. Would you like to resume it?

The poor error message should be addressed by #469.

Sorry for the delay responding you.
