### ISSUE TITLE
Build: Auto generate AUTHORS.txt

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#487]
Ref: https://github.com/jquery/jquery

**Comment by karan1276** [comment]
I did some research and the code below does the trick:
```git shortlog -sne | cut -f 2 | sort | uniq```
I am not sure how exactly can i implement this, i mean it's git command, how can we include this in the jquery workflow, or should i write a grunt task or something for this?
any advice @rxaviers ?

**Comment by rxaviers** [comment]
Thanks @karan1276, that's the idea. jQuery projects automate this by using a grunt task: https://github.com/scottgonzalez/grunt-git-authors. Usage reference: https://github.com/jquery/jquery-ui/blob/master/Gruntfile.js.

**Comment by karan1276** [comment]
Hello @rxaviers, 
Thanks for replying! I am a student pursuing engineering in computer science and there are lots of things i am still learning :smile: 
This issue will be solved easily by a seasoned developer but may take me a day or two :sweat_smile: , i'm just letting you know that i am working on this but i may be a little slow.
 
Thank you for cooperating :smile:

**Comment by rxaviers** [comment]
Take your time and just let me know if you need any guidance. Thanks so far for your willing to contribute.

PS: This may be a good reading https://github.com/jquery/globalize/blob/master/CONTRIBUTING.md
