### ISSUE TITLE
Could not get the values of days and months of a calendar in specified locale as in Globalize 0.9x

### ISSUE THREAD

**Issue by Karthick-NR** [jquery/globalize#491]
I was trying a sample using version 1.0 and i have tried formatting the date using formatDate() and its fine, but my requirement for a use case i could not retrieve the days and months in the specified locale in using the current source. i was succeeded trying the old version 0.9x by using Globalize.culture("en-US").calendar vales which gives the patterns,days and months . 

how could i make this workable?

**Comment by rxaviers** [comment]
// Formatting a standalone day:
Globalize("en").formatDate(new Date(), {raw: "d"});
// > '26'

// Formatting a standalone month;
Globalize("en").formatDate(new Date(), {raw: "M"});
// > '8'
Globalize("en").formatDate(new Date(), {raw: "MM"});
// > '08'
Globalize("en").formatDate(new Date(), {raw: "MMM"});
// > 'Aug'
Globalize("en").formatDate(new Date(), {raw: "MMMM"});
// > 'August'
Globalize("en").formatDate(new Date(), {raw: "MMMMM"});
// > 'A'

// Formatting day and month together:
Globalize("en").formatDate(new Date(), {skeleton: "MMMd"})
// > 'Aug 26'

Did I answer your question? You can find more information about formatDate (or dateFormatter) options at:
https://github.com/jquery/globalize/blob/master/doc/api/date/date-formatter.md

**Comment by Karthick-NR** [comment]
Hi @rxaviers,

Thanks for your update. 

But unfortunately my question is not about formatting dates. i need to get all the month vales for specific culture though code not through JSON available in the cldr data folder. previously in version 0.9x "Globalize.culture("en-US").calendars.standard.months

![console-code](https://cloud.githubusercontent.com/assets/13884205/9492592/7fc382b4-4c16-11e5-928f-b666c6fd6743.PNG)

![console-op](https://cloud.githubusercontent.com/assets/13884205/9492593/7fc4d1a0-4c16-11e5-923c-2b2b4a158ce4.PNG)

" returns the values of all days in the culture.

attached the screenshots of the code to execute and the resultant output in 0.9x for your reference.

**Comment by rxaviers** [comment]
Ok, I have two answers for you. But, can you tell me more about your use case first? Where are you using the month names at?

**Comment by Karthick-NR** [comment]
I am building a datepicker ui component where the locale month data should be changed when i select a particular culture. 

equivalent to this example in jquery ui. https://jqueryui.com/datepicker/#localization . but i am not using jquery ui datepicker.

**Comment by rxaviers** [comment]
Ok, the two ways I've referred earlier are:
 0. Use CLDR data directly.
 0. Use date formatters. (recommended)

**Use CLDR data directly**

Example using node.js and npm:

    npm install globalize cldr-data

```js
var Globalize = require( "globalize" );
Globalize.load(require("cldr-data").entireSupplemental(), require("cldr-data").entireMainFor("en"));
Globalize.locale("en");
Globalize.cldr.main("dates/calendars/gregorian/months/format/wide");
// > { '1': 'January',
//   '2': 'February',
//   '3': 'March',
//   '4': 'April',
//   '5': 'May',
//   '6': 'June',
//   '7': 'July',
//   '8': 'August',
//   '9': 'September',
//   '10': 'October',
//   '11': 'November',
//   '12': 'December' }
```
This solution won't allow you to use the optimal [runtime modules and compilation](https://github.com/jquery/globalize/#compilation-and-the-runtime-modules) for production, unless you write your own compiler.

**Use date formatters**

Example using node.js and npm:

```js
var Globalize = require( "globalize" );
Globalize.load(require("cldr-data").entireSupplemental(), require("cldr-data").entireMainFor("en"));
Globalize.locale("en");

var formatter = Globalize.dateFormatter({raw: "MMMM"});
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].map(function(month) {
  return fmt(new Date(0, month))
});
// > [ 'January',
//   'February',
//   'March',
//   'April',
//   'May',
//   'June',
//   'July',
//   'August',
//   'September',
//   'October',
//   'November',
//   'December' ]
```

This code may look more complex. But, it will actually save you a lot of troubles. Here, you can use the runtime modules mentioned above and eventually you can replace Globalize by native Ecma-402 formatters.
