### ISSUE TITLE
Extra characters tolerated in dateParse and numberParse

### ISSUE THREAD

**Issue by alienintheheights** [jquery/globalize#492]
Using 1.0.0. It seems that gibberish input is getting parsed instead of returning null/NaN.

locale = "pt_BR";
value = "12:12 am sdfsdf33dfllsdf lll;;lk";
Globalize(locale).dateParser({time:"short"})(value)

=> Wed Aug 26 2015 12:12:00 GMT-0500 (CDT)

How is this valid?

Similarly,

locale = "en";
value = "123123 sdfsdf;;dfllsdf";
Globalize(locale).numberParser()(value)

=> 123123

Shouldn't Globalize object to this sort of input??

**Comment by alienintheheights** [comment]
Any thoughts on this? Thanks.

**Comment by rxaviers** [comment]
I will definitely consider pull requests making the parser less permissive.

For the date parser, you may want to check the [date/tokenizer-properties.js](https://github.com/jquery/globalize/blob/master/src/date/tokenizer-properties.js) and the [date/tokenizer.js](https://github.com/jquery/globalize/blob/master/src/date/tokenizer.js).

For number parser, you may want to check #353.

**Comment by rxaviers** [comment]
Closing this issue since this isn't a bug [1]. This can still be used to discuss any API change for the optional less permissive parsing. PRs welcome.

1: JavaScript has similar behavior in what's regard extra characters tolerated in some situations.

```js
> parseFloat('123 asd')
123
> parseFloat('asd 123')
// NaN
```
