### ISSUE TITLE
Parse date with custom format

### ISSUE THREAD

**Issue by ivan-kleshnin** [jquery/globalize#500]
I need to parse date in format "year-month-day", for example "2011-01-01".
How can I do that?

https://github.com/jquery/globalize/blob/master/doc/api/date/date-formatter.md

Describes a lot of options but noone seems to support custom separators for parsing.
I expected to use `skeleton` but it turns out to be of the same rigid presets.

This is very strange unless I missed something.
There is no "standard" separator for date in Russian locale, for example.
We use "-" as frequent as "/".

**Comment by rxaviers** [comment]
Use the `raw` option to pass the `raw pattern` directly. This is acceptable if you are parsing a rigid format that never changes on different locales, which I guess is the case. You might want to use `{raw: "y-MM-dd"}`.

Feel free to add new comments on any questions.

**Comment by rxaviers** [comment]
Is there anything on https://github.com/jquery/globalize/blob/master/doc/api/date/date-formatter.md you would change to it clear?

**Comment by ivan-kleshnin** [comment]
I missed this `raw` modifier entirely, cause it is in gray color and there is no corresponding example for it.
Also there is no visible placeholder value for digital month (`MM` you gave up).

**Comment by rxaviers** [comment]
Thanks for identifying the places that need improvement. It would be of extreme help if you could also provide the improved text, so we could update the current documentation.

About the pattern for digital month, yeap there's no explicit example for all the patterns. All we have is a `raw pattern` link to the full list http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table. I am open to suggestions.

Thanks so far.

**Comment by jzaefferer** [comment]
I think this can be reopened as a docs issue.

**Comment by jzaefferer** [comment]
The example for `raw` actually contains this as an example, that looks wrong: `{ pattern: "dd/mm" }`. This should be `{ raw: "dd/mm" }`, right? 

The link behind "raw pattern" doesn't seem too useful, since its unclear how to read that table, for example, which column is relevant for this option? Making that more explicit, e.g. "[link raw pattern] (look at the "Sym." column to find the relevant symbols)" (if that's the right one), should help.

Fixing those should help. Adding an example might do more harm than good, since we really don't want to promote this option for general use.

**Comment by rxaviers** [comment]
> The example for raw actually contains this as an example, that looks wrong: { pattern: "dd/mm" }. This should be { raw: "dd/mm" }, right? 

Right.

> The link behind "raw pattern" doesn't seem too useful, since its unclear how to read that table, for example, which column is relevant for this option

Why? Every columns are relevant. All patterns could be used.

> Adding an example might do more harm than good, since we really don't want to promote this option for general use

I agree we should not promote using the `raw` option, but `skeleton`. Although, note that both `raw` and `skeleton` (the one we encourage) uses the same patterns.

**Comment by jzaefferer** [comment]
> Every columns are relevant.

Can I use "year" in a pattern? Or "quarter"? That's what the first column contains. As far as I can tell, the "Sym." column is the important one.

I also fixed my last comment to not render the proposed markdown, hopefully now my suggestion makes more sense.

**Comment by rxaviers** [comment]
> Can I use "year" in a pattern? Or "quarter"? That's what the first column contains. As far as I can tell, the "Sym." column is the important one.

Yeap, in the unicode table, the `Field` column has a short description, the `Sym.` column has the actual pattern, and the `No.` column has the number of times you need to repeat a pattern to change its form (e.g., Q or QQ for the numerical form of quarter, QQQ for the abbreviation, etc as described by the `Description` column). By the way, your edited comment makes more sense :).

Basically, I am open to all changes that clarify the documentation.

**Comment by rxaviers** [comment]
Having said the above, I don't think though it's positive to keep a bunch of issues like this open if no one is willing to fix it.
