### ISSUE TITLE
Unwanted rounding with numberFormatter and percent style.

### ISSUE THREAD

**Issue by wescravens** [jquery/globalize#504]
`Globalize.numberFormatter({style: 'percent'})(0.005);` in `en` should show 0.5% but instead shows 1%.  

Is it possible to make the rounding configurable or make use of `minimumFractionDigits` and `maximumFractionDigits` with `{style: 'percent'}`?  Sorry if this already exists, but I've been scouring the docs for the last hour and can't find anything.

**Comment by jzaefferer** [comment]
@rxaviers what do you think?

**Comment by rxaviers** [comment]
What's wrong with the current implementation? It works for me:

```js
Globalize('en').formatNumber(0.005, {style: 'percent', minimumFractionDigits: 1, maximumFractionDigits: 1});
// > '0.5%'
```

**Comment by rxaviers** [comment]
>  Sorry if this already exists, but I've been scouring the docs for the last hour and can't find anything.

No problem. Is there anything you would improve in the current documentation? We are open to suggestions. Thanks!

**Comment by jzaefferer** [comment]
How about adding a `style: "percent"` example to https://github.com/jquery/globalize/blob/master/doc/api/number/number-formatter.md ? Currently this page only mentions that the value exists, but there's nothing else.

**Comment by rxaviers** [comment]
@wescravens does @jzaefferer suggestion help you? Anything else?

**Comment by wescravens** [comment]
@rxaviers @jzaefferer Weird, I just tried again and it works as expected.  There may have been some other issue going on with another filter as we are using this in a Angular filter that allows for other filters to transform the number before it makes it to the percentage filter.  Thanks for the help though.  I would like to see a more in-depth example of the percentage formatter in the docs, but other than that, I think we're good to go.  Thanks!

**Comment by rxaviers** [comment]
Thanks for the update @wescravens. Indeed it would be great if we had more percentage examples in the docs. Would you like to help by sending us a pull request with such changes?

**Comment by wescravens** [comment]
@rxaviers Yeah I'll work on that tonight.  Thanks!

**Comment by rxaviers** [comment]
Awesome, thank you.
