### ISSUE TITLE
json.zip not available anymore

### ISSUE THREAD

**Issue by leus** [jquery/globalize#505]
The [documentation](https://github.com/jquery/globalize/blob/1.0.0/doc/cldr.md) needs changing because the json.zip package is not updated anymore in the "data link" (don't you love old corp lingo?)

The latest available version is 26:
http://www.unicode.org/Public/cldr/26/

From 27 and on there is no json package:
http://www.unicode.org/Public/cldr/27/

They [announced this](http://www.unicode.org/Public/cldr/27/) and didn't even apologized for breaking links. Supposedly everything can be found [not far from here](https://github.com/unicode-cldr/cldr-json), but good luck with that.

(Globalize 0 was _so much easier to use_. I've been chasing this crud all morning.)

**Comment by rxaviers** [comment]
Hi, thanks for pointing it out. But, this same page has already been updated: https://github.com/jquery/globalize/blob/master/doc/cldr.md :smile: 

The link you are using points to an older point in time of the documentation.
