### ISSUE TITLE
numberFormatter({ maximumFractionDigits: 0 }) returns digits with small values

### ISSUE THREAD

**Issue by juhamust** [jquery/globalize#510]
Consider following inputs and outputs:
```javascript
Globalize.numberFormatter({ maximumFractionDigits: 0 })(100); // Output: 100.00
Globalize.numberFormatter({ maximumFractionDigits: 0 })(1000); // Output: 1 000
```

**Comment by juhamust** [comment]
Uh, wrong call. I had *additional* formatter in place causing the odd behaviour. After removing it, the outcome works as expected.

Shame on me.

**Comment by rxaviers** [comment]
No problem. If you find any problems, please just let us know. Thanks
