### ISSUE TITLE
Does globalize have the ability to tell me the display name of a language from a language code?

### ISSUE THREAD

**Issue by miracle2k** [jquery/globalize#513]
I.e. a version of this:

https://gist.github.com/mirontoli/4722797

**Comment by rxaviers** [comment]
Yes, please read http://stackoverflow.com/a/32142568/798133 to understand what's `cldr` I'm using below. Then, you can:

```js
cldr.main(['localeDisplayNames/languages/', language]);
cldr.main(['localeDisplayNames/languages/', 'pt']);
// > 'Portuguese' when cldr is using the `en` locale.
```

For showing the display name of the current locale, use:
```js
cldr.main('localeDisplayNames/languages/{language}');
```

Please, just let me know if you have any questions.

If it's clear, please how can we improve our docs to help further users to figure this out?

Thanks

**Comment by johnnyreilly** [comment]
Hi @rxaviers,

Based on this I'd imagine that the following should work:

```
Globalize.locale().main('localeDisplayNames/languages/de-CH');
```

when de-CH is the default locale and return "German".  But it returns `undefined`.  Did I miss something?  

Also, how do you get the "Swiss" part - the region rather than the language?

**Comment by rxaviers** [comment]
This is correct and you should get `Schweizer Hochdeutsch`. Have loaded `main/de-CH/languages.json` content?

**Comment by johnnyreilly** [comment]
I hadn't - [attempting now](https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native/commit/c65d27f76fe6edfd4b24eebe6323e095e3f80001)

**Comment by johnnyreilly** [comment]
No dice. I'm loading `languages.json` but it makes no difference.  You can see it not working here: (look at `undefined` to the right of dropdown) http://johnnyreilly.github.io/jQuery.Validation.Unobtrusive.Native/AdvancedDemo/Globalize.html

**Comment by rxaviers** [comment]
Well, it should work. See below a quick demonstration. Ping me on IRC, so I can help you debug what's going wrong in your case.

    npm install globalize cldr-data
    node

```js
Globalize = require('globalize');
// Alternatively, load them all:
// Globalize.load(require('cldr-data').entireSupplemental());
// Globalize.load(require('cldr-data').entireMainFor('en'));
Globalize.load(require('cldr-data/supplemental/likelySubtags'));
Globalize.load(require('cldr-data/main/en/languages'));
Globalize.locale('en');
Globalize.locale().main('localeDisplayNames/languages/de-CH');
// > 'Swiss High German'

// Alternatively, load them all: Globalize.load(require('cldr-data').entireMainFor('en'));
Globalize.load(require('cldr-data/main/de-CH/languages'));
Globalize.locale('de-CH');
Globalize.locale().main('localeDisplayNames/languages/de-CH');
// > 'Schweizer Hochdeutsch'
```

**Comment by johnnyreilly** [comment]
Sorry I missed you - went to bed!

Here's my setup.   These are the Globalize / cldr files I have loaded:

```
        "~/bower_components/cldrjs/dist/cldr.js",
        "~/bower_components/cldrjs/dist/cldr/event.js",
        "~/bower_components/cldrjs/dist/cldr/supplemental.js",
        "~/bower_components/globalize/dist/globalize.js",
        "~/bower_components/globalize/dist/globalize/number.js",
        "~/bower_components/globalize/dist/globalize/date.js",
```

Your example says `require('globalize');` - does that include extra globalize modules I haven't included above that are required?

The json data is loaded on demand via AJAX and is driven by the following mechanism:

```js
    function getJsonFilenames(locale, loadedData) {

        return [
            "supplemental/likelySubtags.json",
            "main/{locale}/numbers.json",
            "supplemental/numberingSystems.json",
            "main/{locale}/ca-gregorian.json",
            "main/{locale}/timeZoneNames.json",
            "supplemental/timeData.json",
            "supplemental/weekData.json",
            "main/{locale}/languages.json"
        ].filter(function (f) {
            var noDataLoaded = loadedData.length === 0;
            if (noDataLoaded) {
                return true;
            }
            var localeNotYetLoaded = loadedData.indexOf(locale) === -1;
            if (localeNotYetLoaded) {
                var fileIsCommonAndSoAlreadyLoaded = f.indexOf("supplemental/" !== -1);
                return fileIsCommonAndSoAlreadyLoaded;
            }
            return false;
        }).map(function (f) { 
            return "../bower_components/cldr-data/" + f.replace("{locale}", locale); 
        });
    }

    function loadLocale(locale, loadedData) {

        var promise = $.Deferred();
        var jsonToLoad = getJsonFilenames(locale, loadedData);
        if (jsonToLoad.length === 0) {
            Globalize.locale(locale); // Presumably already loaded
            promise.resolve(locale + " selected...")
            return promise;
        }

        return $.when.apply(
            this, jsonToLoad.map($.get)
        ).then(function () {
            // Normalize $.get results, we only need the JSON, not the request statuses.
            return [].slice.apply(arguments, [0]).map(function (result) {
                return result[0];
            });
        }).then(Globalize.load).then(function () {
            loadedData.push(locale);
            Globalize.locale(locale);
            return locale + " loaded and selected..."
        });
    }

    var localesLoaded = [];

    $("#localeSelector").change(function () {
        var $this = $(this);
        var $exampleFormats = $("#exampleFormats");
        var $loading = $("#loading");

        $this.prop("disabled", true);
        $loading.show();
        $exampleFormats.hide();
        
        var localeToLoad = $this.val();

        loadLocale(localeToLoad, localesLoaded)
            .then(function (result) {
                $this.prop("disabled", false);
                $loading.hide();
                var languageName = Globalize.locale().main('localeDisplayNames/languages/' + locale);
                var exampleFormats = languageName + ": A number may look like this: " + Globalize.numberFormatter()(11.7) +
                    " and a date may look like this: " + Globalize.dateFormatter()(new Date());
                $exampleFormats.text(exampleFormats).show();
            }, function (error) {
                $exampleFormats.text("Problem loading locale: " + error).show();
                $this.prop("disabled", false);
                $loading.hide();
            });
    }).change();
```

Essentially, as users select a locale the relevant json will be loaded and then selected as the default. Common json (`likelySubtags.json` etc) are only loaded once and if a locale has been previously loaded it is not reloaded it is just selected.

Beyond the loading mechanism is there a difference between your node / webpack / browserify style code and my jQuery AJAX style code?

**Comment by rxaviers** [comment]
> Here's my setup. These are the Globalize / cldr files I have loaded:

The modules you're loading are enough.

> Beyond the loading mechanism is there a difference between your node / webpack / browserify style code and my jQuery AJAX style code?

There's a difference. But, it should not matter for Globalize functioning.

@johnnyreilly can you create a gist with you code with, so I can clone it and reproduce it locally?

**Comment by johnnyreilly** [comment]
Hi @rxaviers,

I was diligently putting together a gist when I realised that the problem wasn't quite what I thought it was.  The functionality **works**.  There's a but.  Not for all regions.  I'll post the Gist if you like but it strikes me that this might be a problem with the cldr data itself rather than an issue with Globalize / cldr...

So if you go to the [demo](https://johnnyreilly.github.io/jQuery.Validation.Unobtrusive.Native/AdvancedDemo/Globalize.html) and select "ar" you get this:

![image](https://cloud.githubusercontent.com/assets/1010525/10308858/bc9eaf58-6c30-11e5-8256-3d136296d734.png)

i.e. a language name (albeit in Arabic - "العربية").  But if you select say "ar-AE" (or frankly any of the other arabic alternatives) then you get nothing:

![image](https://cloud.githubusercontent.com/assets/1010525/10308885/ec327b28-6c30-11e5-8b37-a236bdc62196.png)

This is intentional I guess?

**Comment by rxaviers** [comment]
@johnnyreilly will read it when I have more time.

**Comment by rxaviers** [comment]
On #524, @aurambaj said:

> Ideally I'd like to avoid accessing CLDR data and rebuild the final string myself.

Something that occurred me is feeding `Globalize.loadMessages()` with the result of `.main('localeDisplayNames/languages/{locale}')` and then using `Globalize.messageFormatter()` to actually format the message. Doing this will allow the usage of static compiler and the runtime modules.

**Comment by johnnyreilly** [comment]
Gist is [here](https://gist.github.com/johnnyreilly/e97b97afa5217e4065a9) BTW.  You'll need to run a simple static file server so it can do the AJAX I think - but that's it (get's everything it needs from the web)

**Comment by rxaviers** [comment]
>  But if you select say "ar-AE" (or frankly any of the other arabic alternatives) then you get nothing

You may want to consider to use the composition form, which would generate `Arabic (United Arab Emirates)`. More information here http://www.unicode.org/reports/tr35/tr35-general.html#Display_Name_Elements

Does it help you out?

**Comment by rxaviers** [comment]
Nice demo by the way

**Comment by johnnyreilly** [comment]
> Nice demo by the way

Thanks!

> You may want to consider to use the composition form, which would generate Arabic (United Arab Emirates). More information here http://www.unicode.org/reports/tr35/tr35-general.html#Display_Name_Elements

> Does it help you out?

I see the link but I'm afraid I don't get your meaning.  There's another way to get the information from the API?

**Comment by rxaviers** [comment]
> I see the link but I'm afraid I don't get your meaning. There's another way to get the information from the API?

The way to get the information is correct. But, the way to use it could be improved as explained by CLDR docs. Please, just let me know on any questions.

**Comment by johnnyreilly** [comment]
Sorry @rxaviers  - I may be being dense but I've no clue what you mean by using the "composition form".  An example might help...  

Are you suggesting doing something like this?:

```
Globalize.locale().main('localeDisplayNames/languages/English (United Kingdom)')
```

I'm guessing not since that would be rather chicken and egg (where would we get "English (United Kingdom)" from in the first place)?

I think I'm missing your point....

**Comment by rxaviers** [comment]
No, what I mean is: you said there's info for `.main('localeDisplayNames/languages/ar')`, but there isn't for `.main('localeDisplayNames/languages/ar-AE')`. So, in your user code, you could first get `.main('localeDisplayNames/languages/{locale}')`. If this is undefined, you could do what @aurambaj is doing here https://github.com/jquery/globalize/issues/524#issuecomment-146042237. In CLDR specs, take a look at `localePattern` and the examples mentioned there. Just let me know on any questions.

**Comment by johnnyreilly** [comment]
Oh I see - thanks.  For the sake of a demo I think I'll leave it as is - if this was something fuller fledged I might take this approach.

It's strange that there are these holes in the data though; any idea why?  It seems like this is something you can workaround using CLDR but you ought not to need to. (Well, that would be my view - if something is a locale then it ought to have the associated data or else what's the point?)

**Comment by rxaviers** [comment]
Ywc. I can understand why not all locales have an explicit translation. It's because, there are tons and tons of different language vs. region vs. other locale variants combinations. So, they include explicit/specific translations for the majority, but not for all, specially the ones that can be deduced (for example by using the composition form discussed earlier) and especially that there might be no clear definition of what all should be (note that `ar-<region>` where region is any region of the world is a valid locale).

**Comment by johnnyreilly** [comment]
Thanks for the in depth help - always appreciated!

**Comment by rxaviers** [comment]
You are welcome, thanks for your interest and help too.
