### ISSUE TITLE
globalize-webpack-plugin does not build on windows

### ISSUE THREAD

**Issue by anaritsin** [jquery/globalize#516]
Unless I am missing something, I don't think globalize-webpack-plugin would build on windows... I am thinking regular expressions might be the problem:

    
    GlobalizeCompilerHelper.prototype.getModuleFilepath = function(request) {
      return path.join(this.tmpdir, request.replace(/.*!/, "").replace(/[/?" ]/g, "-"));
    };

**ERROR in ./app/index.js**
Module parse failed: C:\app-npm-webpack\app\index.js ENOENT, no such file or directory 'C:\app-npm-webpack\.tmp-globalize-webpack\C:\app-npm-webpack\app\index.js'
You may need an appropriate loader to handle this file type.
Error: ENOENT, no such file or directory 'C:\app-npm-webpack\.tmp-globalize-webpack\C:\app-npm-webpack\app\index.js'

**Comment by jzaefferer** [comment]
Classic Windows path issue. Should be easy enough to fix. While at it, set up CI on Windows? http://www.appveyor.com/ makes that reasonably easy.

**Comment by rxaviers** [comment]
@anaritsin thanks for reporting. Moving this issue to https://github.com/rxaviers/globalize-webpack-plugin/issues/7. Would you like to contribute a fix. if so, I can review and point you to the places that need change. Thx

**Comment by anaritsin** [comment]
Hi Rafael,

Yes, I would like to try to make it work on Windows as this is our dev
environment. I'd appreciate if you could give me some guidance.
I tried a quick&dirty fix,

GlobalizeCompilerHelper.prototype.getModuleFilepath = function(request) {
  return path.join(this.tmpdir, request.replace(/.*!/,
"").replace(/[/?" \\:]/g, "-"));
};

but it goes one step farther and fails at

ERROR in ./.tmp-globalize-webpack/C--app-npm-webpack-app-index.js

Module not found: Error: Cannot resolve module
'globalize-runtime/number' in
C:\app-npm-webpack\.tmp-globalize-webpack

 @ ./.tmp-globalize-webpack/C--app-npm-webpack-app-index.js 7:2-192


I am assuming it has something to do with the skip-amd-webpack-plugin
not being used properly.

if i mess with the compile.template to remove the AMD define (bad
thing to do!), it actually builds,  but does not run.

I'd like to try to make it work properly.


thx,
Anatoly

**Comment by rxaviers** [comment]
Reply at https://github.com/rxaviers/globalize-webpack-plugin/issues/7#issuecomment-144794603
