### ISSUE TITLE
Does Globalize / CLDRJS have a concept of a friendly display name for a locale?

### ISSUE THREAD

**Issue by johnnyreilly** [jquery/globalize#519]
ie where "en-GB" would be "UK English" an "de-CH" might be "Swiss German" or something?

I'm working on a demo for [https://github.com/johnnyreilly/jquery-validation-globalize](https://github.com/johnnyreilly/jquery-validation-globalize) (now on 1.x).  It'd be nice to have something that's a little more user friendly to display in the demo when they pick a culture...

I tried `attributes` but that doesn't really have what I'm after

```
Globalize.locale().attributes
{"bundle":"de","minlanguageId":"de","maxLanguageId":"de-Latn-DE","language":"de","script":"Latn","territory":"DE","region":"DE"}
```

**Comment by rxaviers** [comment]
Hi @johnnyreilly, it's a dup of #513. Please, feel free to add comments there if you have any further questions.
