### ISSUE TITLE
Function to get a locale display name

### ISSUE THREAD

**Issue by aurambaj** [jquery/globalize#524]
Hi,

I'm wondering if there is a function to display a user friendly name of locale in a give locale. The equivalent of that Java code:

```
Locale forLanguageTag = Locale.forLanguageTag("fr-FR");
String displayName = forLanguageTag.getDisplayName(Locale.forLanguageTag("zh-CN"));
// 法文 (法国)
```

I guess this can all be extracted from CLDR. I also see that there is a pattern (sounds like it is always the same though):
```
"localeDisplayNames": {
        "localeDisplayPattern": {
          "localePattern": "{0} ({1})",
```
Ideally I'd like to avoid accessing CLDR data and rebuild the final string myself. 

Thanks!

**Comment by rxaviers** [comment]
Hi @aurambaj, it's a dup of #513. Please, feel free to add comments there if you have any further questions.

**Comment by aurambaj** [comment]
What I wanted is slightly different. I want the locale representation: `language (country/territory)` not just the language.

Came up with this code so far: 
```
getDisplayName(bcp47Tag) {
        let cldr = new Cldr(bcp47Tag);

        let language = cldr.attributes.language;
        let territory = cldr.attributes.territory;

        let languageDisplay = this.userCldr.main("localeDisplayNames/languages/" + language);
        let territoryDisplay = this.userCldr.main("localeDisplayNames/territories/" + territory);
        let pattern = this.userCldr.main("localeDisplayNames/localeDisplayPattern/localePattern");

        return simpleFormat(pattern, languageDisplay, territoryDisplay);
}
```

**Comment by rxaviers** [comment]
I see, you want to use the composition form. CLDR allows for different usage variations of the Display Name Elements. Anyway, I still think #513 could be used to discuss them all. FWIW, this might be useful in general: http://www.unicode.org/reports/tr35/tr35-general.html#Display_Name_Elements

About your code snippet...

1. I would consider the following change:

```diff
diff --git a/code b/code
index 6b385bd..b87114a 100644
--- a/code
+++ b/code
@@ -1,12 +1,9 @@
 getDisplayName(bcp47Tag) {
-        let cldr = new Cldr(bcp47Tag);
+        const cldr = new Cldr(bcp47Tag);
 
-        let language = cldr.attributes.language;
-        let territory = cldr.attributes.territory;
-
-        let languageDisplay = this.userCldr.main("localeDisplayNames/languages/" + language);
-        let territoryDisplay = this.userCldr.main("localeDisplayNames/territories/" + territory);
-        let pattern = this.userCldr.main("localeDisplayNames/localeDisplayPattern/localePattern");
+        const languageDisplay = cldr.main("localeDisplayNames/languages/{language}");
+        const territoryDisplay = cldr.main("localeDisplayNames/territories/{territory}");
+        const pattern = cldr.main("localeDisplayNames/localeDisplayPattern/localePattern");
 
         return simpleFormat(pattern, languageDisplay, territoryDisplay);
 }
```

Specially, note the short form `cldr.main("localeDisplayNames/languages/{language}")` (and similar for territory). You can reference any attributes in the path by wrapping them by curly braces `{}`.

Also note that you could be interested in composing more information that language and territory only, like currency code, etc, e.g.,  the display of `zh_Hant_CN_co_pinyin_cu_USD` would be `"Chinese (Traditional, China, Pinyin Sort Order, Currency: USD)"`.

**Comment by aurambaj** [comment]
@rxaviers Thanks for the pointers, that helps!!
