### ISSUE TITLE
Get the raw string from the loaded messages

### ISSUE THREAD

**Issue by gcastre** [jquery/globalize#536]
Hello,

In the JSON containing my localized messages I have some messages that I need to set to other plugins. Those lines sometimes contains some args (aka: Hello {0}).

In globalize 0.x I could get the raw value of my message, but now the plugin throw an exception if I don't pass the args with the formatMessage()

Is there a way to bypass the formatting step and simply get the raw value  ?

**Comment by gcastre** [comment]
To solve this you must use
```js
Globalize.locale().get("globalize-messages/{bundle}/your/path/to/the/message")
```

**Comment by rxaviers** [comment]
Sorry for the delay, your self-answer is correct.
