### ISSUE TITLE
date dependency

### ISSUE THREAD

**Issue by Mottie** [jquery/globalize#543]
According to the [Pick the modules you need](https://github.com/jquery/globalize#pick-the-modules-you-need) section in the main readme it sound like each module is independent of other modules.

I created [this demo](http://jsfiddle.net/Mottie/gf3nu9q6/3/) to format a date... `number.js` isn't needed, but it is loaded *after* `date.js` and this error appears in the console:

> Uncaught TypeError: numberSymbol is not a function ... date.js:593

which corresponds to this line: https://github.com/jquery/globalize/blob/master/src/date/format-properties.js#L25

Just to confirm my suspicions, [this demo](http://jsfiddle.net/Mottie/gf3nu9q6/4/) loads `number.js` before `date.js` and it works without any problems.

----

I should probably open a new issue for this, but would you consider including one big Globalize file that contains all the modules?

**Comment by jzaefferer** [comment]
> According to the Pick the modules you need section in the main readme it sound like each module is independent of other modules.

As far as I can tell, that's wrong. There are several dependencies across modules, and the documentation should make that explicit.

**Comment by johnnyreilly** [comment]
It does... but not there.  If you look at https://github.com/jquery/globalize#2-cldr-content this becomes more apparent.  For a visual representation of what module depends on what, take a look at [here](http://johnnyreilly.github.io/globalize-so-what-cha-want/)

**Comment by Mottie** [comment]
It's still not explicitly stated anywhere. That's a nice tool @johnnyreilly, but it wasn't the first place I looked.

And my other point was that the number module *must* be loaded first, or the date module throws an error.

**Comment by johnnyreilly** [comment]
It may not be clear from the tool but the order in which files are listed is the order in which are required.

But yeah, the docs could perhaps be a little clearer.  Do you have a suggestion?  A docs PR wouldn't take long to turn around...
