### ISSUE TITLE
Inconsistencies in parsing invalid date values

### ISSUE THREAD

**Issue by martinknafve** [jquery/globalize#550]
I'm having some issues understanding the rules when it comes to parsing invalid date strings. I'm using the sv-se locale.

If I parse the value 2015-02-30 using skeleton yMd, then 2015-02-28 is returned.
If I parse the value 2015-13-02 using same skeleton, then null is returned.

I would expect that if the date string does not match the skeleton then null is returned rather than an actual date with invalid month/day.

Is this a bug in the date parser?

**Comment by rxaviers** [comment]
Yeap, results should be consistent. Values ranges are tested by the parser, e.g., month range is tested at https://github.com/jquery/globalize/blob/master/src/date/parse.js#L105-L107, but day of month isn't: https://github.com/jquery/globalize/blob/master/src/date/parse.js#L118-L121.

We should definitely test for the day ranges too. Are you interested in providing this fix? Please, feel free to send a pull request or let me know if you need any help to.

Thanks

**Comment by martinknafve** [comment]
Sure, I'll submit a PR.

**Comment by globalizer** [comment]
Sorry - turned out that this was an error on my side. Apparently I'm using an older version and this issue has already been resolved. It's handled here:

https://github.com/jquery/globalize/blob/master/src/date/parse.js#L251-L253

This issue can be closed.

**Comment by martinknafve** [comment]
Sorry - turned out that this was an error on my side. Apparently I'm using an older version and this issue has already been resolved. It's handled here:

https://github.com/jquery/globalize/blob/master/src/date/parse.js#L251-L253

This issue can be closed.

**Comment by rxaviers** [comment]
Aha! Even better. :) Thanks
