### ISSUE TITLE
Webpack example is not working

### ISSUE THREAD

**Issue by zamap** [jquery/globalize#551]
just tried to build and run globalize\examples\app-npm-webpack. I have got an error in browser console 'Uncaught TypeError: Globalize.load is not a function

**Comment by rxaviers** [comment]
Can you provide a little more details? What's your environment (OS, npm and node versions)? What command did you run to get this error (development or production mode)?

**Comment by zamap** [comment]
dev mode, windows,npm 2.14.7, node v4.2.1

**Comment by gentilim** [comment]
Seeing the same thing with `npm run start` on Windows 8, node@5.1.0, npm@3.5.0.

**Comment by rxaviers** [comment]
Closing in favor of https://github.com/rxaviers/globalize-webpack-plugin/issues/7
