### ISSUE TITLE
How do I format the year with two digits?

### ISSUE THREAD

**Issue by andersem** [jquery/globalize#556]
I want to format 2015 as 15, how do I do this? Reading https://github.com/jquery/globalize/blob/master/doc/api/date/date-formatter.md doesn't help.

**Comment by rxaviers** [comment]
Hi,

First things first, let's identify how we can improve the documentation. Can you provide details on how far the documentation helped you (e.g., which date-formatter option would allow you do so) and where your it leaves your question unclear?

Thanks

**Comment by jzaefferer** [comment]
I clicked on that, then on the link inside the skeleton description, where I found `yy` in the big table, which seems like the right skeleton for the requested format.

I think the link is very subtle and easy to miss, "date field" is not the same as "For a full list of all pieces that make up a pattern, GO HERE".

**Comment by rxaviers** [comment]
@andersem does the above clarify it? Any additional suggestions?

**Comment by andersem** [comment]
That clarifies it. Thank you. :)

I actually was inside that page @jzaefferer is talking about, but I missed that table inside the table showing what different number of y's gives me. I just saw this and thought: "Okay, is this everything?" I was also in a hurry, so I couldn't read everything on every page that I was inside.
![table](https://cloud.githubusercontent.com/assets/509817/11436701/6ed3878c-94e7-11e5-828b-6781c4d93f21.png)

I'll try giving you an insight into my way of thinking and how the documentation helped me:

The reason I'm using globalize is because I'm using another library that forces me to. So I first had to read their docs, then I had to go to your docs because I didn't understand how to load cldr-data. I didn't even have a clue what cldr-data was. I finally understood (after fiddling with npm install --save cldr-data that didn't at first download the actual data, which again gave me errors when trying to load the jsons.)

After successfully loading the english data, I tried loading norwegian. The country codes available to me weren't specified anywhere, and norwegian normally has a bunch of options: no, nb-no, no-nb, nb, nn-no, no-nn etc, so it wasn't the easiest guess.

I then went to the formatting. I understood that I should go to dateformatting, and that I should click on Read more. I expected something like this: http://momentjs.com/docs/#/displaying/format/, but instead I was given format strings like: GyMMMd, full, medium and Ehms. I guess some people might be interested in that, but I needed to do things my way, and it wasn't obvious how to. I also found the term "skeleton" strange: "Why would I have to understand that term just to be able to format something?" Googling around brought me to http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table. I skimmed the list, but as mentioned earlier, I didn't find the correct table inside the table. 

Then I came here, and you answered very quickly. Thank you for that :)

**Comment by rxaviers** [comment]
@andersem, Your insight helped tremendously.

I've started a pull request improving our docs about the points you mention. For instance: (a) a quick example in the beginning of Getting Started that should provide the easiest way to load cldr-data for playing with Globalize; (b) more information about locale and examples along with descriptions. It still needs improvements, specially for the date format patterns.

Help appreciated: https://github.com/jquery/globalize/pull/557

**Comment by rxaviers** [comment]
I'm landing #557 for now. It would still be good if you could check whether that helps clarifying your questions (at least, part of your questions).

Fixing this issue still requires additional updates. Help appreciated.

**Comment by andersem** [comment]
Hi, sure thing.

Sorry I didn't have time to go through your pr.

**Comment by andersem** [comment]
From what I read now, everything seems to help. I didn't see a more visible link to the full skeleton-section.

**Comment by rxaviers** [comment]
No problem and yeap, the changes on the API doc is still needed, so I'm reopening it.

**Comment by rxaviers** [comment]
I'm glad to know the partial changes are helping already.
