### ISSUE TITLE
module dependecies switched in currency module

### ISSUE THREAD

**Issue by Songissimo** [jquery/globalize#560]
Hi, in currency module ("src/currency.js") the following dependencies in the "define" were switched:
- "./common/validate/parameter-type/currency"
- "./common/validate/parameter-type/number"
the number validator should be placed before the currency.

This is causing problems when currency filter is used.

**Comment by rxaviers** [comment]
Hi, thanks for filing this issue.

Which currency filter? Could you provide me a short example of the problem you're experiencing?

Thanks

**Comment by Songissimo** [comment]
Pretty simple, Under branch "320-nongregorian" open file "globalize/src/currency.js", you'll notice that dependencies listed do not match the parameters in the define function.
Problem is in "Globalize.prototype.currencyFormatter" when calling "validateParameterTypeCurrency"

**Comment by rxaviers** [comment]
Ouch, that is an ugly one. Thanks for spotting it. A fix is on the way...

**Comment by rxaviers** [comment]
Fixed and released as 1.1.0-rc.7. Please, just let me know if you find anything else.
