### ISSUE TITLE
Globalize 1.0.0 does not work the the latest es5-shim

### ISSUE THREAD

**Issue by Nexith** [jquery/globalize#561]
When using ```globalize 1.0.0``` with the latest ```es5-shim``` it throws ```throws new TypeError(ERR_ACCESSORS_NOT_SUPPORTED);``` on line 55 in plural.js.

I first created an issue in the ```es5-shim``` repo, see: es-shims/es5-shim#363 for more information.

**Comment by ljharb** [comment]
Note that this means globalize doesn't support IE 8, which has defineProperty but does not support defining properties on non-DOM elements.

**Comment by rxaviers** [comment]
This regression has been introduced by 7e1cee3b, which updated make-plural from `2.1.2` to `3.0.0`. So, the last Globalize that was compatible with IE8 was `1.0.0-alpha.20`.

**Comment by rxaviers** [comment]
FWIW, this regression should affect the plural module only.

**Comment by rxaviers** [comment]
I plan a patch fix `1.0.1` that will bring back support for IE8. PR #579.

**Comment by ericelliott** [comment]
Looks like that PR was merged. Should this issue be closed?

**Comment by rxaviers** [comment]
Yeap, thanks

**Comment by rxaviers** [comment]
`1.0.1` has been released.
