### ISSUE TITLE
numberParser issue with parsing numbers

### ISSUE THREAD

**Issue by Jcomper** [jquery/globalize#564]
Hi, I'm trying to parse numbers in Swedish locale and got unexpected results:

    var globalize = Globalize("se-SE");
    var numberParser = globalize.numberParser({ minimumFractionDigits: 2 });
    var numberFormatter = globalize.numberFormatter({ minimumFractionDigits: 2 });
    		
    console.log(numberFormatter(395839.580)); // outputs 395 839,58
    console.log(numberParser("395839,580")); // outputs 395839.58
    console.log(numberParser("395 839,58")); // expected 395839.58, but outputs NaN

Why formatting the number working well but parsing that number returns NaN?

**Comment by rxaviers** [comment]
Please, can you try the below and let me know your output?

```js
numberParser(numberFormatter(395839.580))
```

**Comment by rxaviers** [comment]
If the above works, check if the blank space (used by the grouping separator) is the same for both your sample code and what you get when formatting.

**Comment by Jcomper** [comment]
Hi,
```javascript
console.log(numberParser(numberFormatter(395839.580))); //outputs 395839.58
```
blank space (grouping separator) looks the same, I've copied output from 
```javascript
console.log(numberFormatter(395839.580));
```
into
```javascript
console.log(numberParser("395 839,58"));
```

and the output is NaN. What I'm trying to reach is bind formatted numbers to inputs and allow user to edit it, but if user edit it with blank space I can't get parsed value.

**Comment by rxaviers** [comment]
Given the inverse operation works, it's working as expected. If you still have any question try checking the character codes of your sample and just let me know.

Having said that, normalizing no-break space to space when parsing is part of what's called Loose matching. It's described at #292 as a new feature to be implemented. We're looking for contributors interested in implementing it. Help appreciated.


https://github.com/jquery/globalize/issues/292

This is what you
