### ISSUE TITLE
Validate locale tag

### ISSUE THREAD

**Issue by GinoPane** [jquery/globalize#568]
Hello!
Sorry, if I missed that, but I can not find an easy way to validate given locale string in order to use it with globalize. E.g. if a locale string is valid and is supported by globalize, then I do other loading stuff, instead of catching errors.

**Comment by rxaviers** [comment]
Please, have you read https://github.com/jquery/globalize#locales? Let me know if that helps and if you have further questions.

**Comment by GinoPane** [comment]
Yeh, I have read that, but it is not exactly what I'm lookng for. 
For example, when calling Globalize('en') we won't get any error, but then, if cldr data for 'en' has not been yet loaded we'd get an error. But in this case we can load 'cldr/datat/en/currencies.json' and so on, because we have such data in cldr set. But what if some of locales missed? And I want to check if I can load valid locale data before actual loading, cause I don't want to get errors. 
For example, currently I have 352 locales in cldr/main/data (I got them after "npm module install cldr-data") so it is obvious that some locales are missing and I can not safely load every locale I want.
So it would be nice to check if necessary locale data is present and then safely load it or jump to fallback with default locale settings.

**Comment by GinoPane** [comment]
I've found availableLocales.json in cldr installation. It seems, that it might be useful to use it for my purpose.

**Comment by rxaviers** [comment]
Gotcha. The answer to your question is still open and lies in https://github.com/rxaviers/cldrjs/issues/30. I suggest we focus any discussion there, so I'm closing this issue here in favor of that. I'd be happy to apply here any outcomes of that issue.
