### ISSUE TITLE
1.1.0 full release

### ISSUE THREAD

**Issue by alunny** [jquery/globalize#569]
Discussed with @rxaviers, but we're seeing multiple issues in our repo with npm's handling of peer dependencies and non-standard release versions.

Sample error:

```
npm ERR! peerinvalid The package globalize@1.1.0-rc.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer default-globalize-messages@0.1.1 wants globalize@>= 1.0.0 || 1.1.0-alpha - 1.1.x
npm ERR! peerinvalid Peer globalize-webpack-plugin@0.2.0 wants globalize@^1.1.0-rc.5
npm ERR! peerinvalid Peer react-globalize-compiler@0.0.6 wants globalize@>=1.0.0 || 1.1.0-alpha - 1.1.x
```

I believe some of the problems are npm bugs, but a 1.1.0 release (without any "-rc" suffix) would be the simplest way to avoid these issues. rc.1 was released back in August, so I don't think it's quite correct to call these release release candidates any more :)

**Comment by jzaefferer** [comment]
1.1.0 and 1.1.0 were released, hopefully the above issues were resolved as well.
