### ISSUE TITLE
Drop IE8 support

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#571]
Currently, IE8 support means two things:
- In the docs, we have instructions for the inclusion of ES5 polyfill in such case;
- In the tests, we have a special trigger for IE8 that uses ES5 polyfill;

We could drop these by dropping support for IE8.

**Comment by jzaefferer** [comment]
You could release 1.1.x as the last minor release to support IE8, then drop it going forward.

**Comment by rxaviers** [comment]
The current IE8 support is currently broken for the plural module (#561). So, I think we should:

1. Officially drop it now for the 1.1.0 release.
1. Release a 1.0.1 with make-plurals reverted back from `3.0.0` to `2.1.2` and skipping any new features like unit formatting and runtime support.

Objections?
