### ISSUE TITLE
Strict parsing dates?

### ISSUE THREAD

**Issue by hippich** [jquery/globalize#576]
I am trying to use `parseDate` to parse dates supplied by user, but I need to catch incorrect dates. While in some cases it is seems to be possible, in others, like date '1/12/123' - is not, due `yy` in en_US locale matching `12` and silently dropping `3`...

Is there any way force strict matching of the value provided?

**Comment by rxaviers** [comment]
Right now there's no way to force strict matching. I think this feature would be welcome.
