### ISSUE TITLE
February Date Parsing

### ISSUE THREAD

**Issue by donlampert** [jquery/globalize#585]
Hello,

I'm running into an issue when parsing dates in Februaries of non-leap years, when the current date is 29-31 of the current month (today is the 29th day of January, for example).  Basically if I choose to parse the date of `2/1/2015` in en with a `date: "short"` format, I get `Sun Mar 01 2015 00:00:00 GMT-0600 (Central Standard Time)`.  This is true for when trying to parse any other day in any other February of non-leap years.  This might not be an issue when we are actually in non-leap year years, as parsing when I set the date variable in `dateParse` to Jan 29, 2015 seems to work with parsing `2/1/2015`.  Parsing `2/1/2016` will work as well.

I'm on the most recent release of globalize, cldrjs, and the cldr-data.  That said, this seems like it was an issue back to at least 1.0 alpha 9.

I plan on investigating this further, but I do appreciate any info or other findings.

Thanks!

**Comment by navels** [comment]
+1!

**Comment by donlampert** [comment]
Thanks @navels, I was seeing this on 1.0.0 as well. I upgraded to 1.1 and saw the same issue. Another project that has 1.0-alpha-9 (😳) was yielding the same, incorrect results. It definitely seems like a special situation that hasn't quite been accounted for/come up before.

**Comment by navels** [comment]
I've submitted a PR: https://github.com/jquery/globalize/pull/586

**Comment by rxaviers** [comment]
Thanks @donlampert for reporting this issue and @navels for the fix.
