### ISSUE TITLE
numberParser test

### ISSUE THREAD

**Issue by jordivila** [jquery/globalize#587]
Hello ,

                esParser("3,14"); // -> 3.14
                esParser("3.14"); // -> 314

Having these lines of code I'd like to know if there is any way the 2nd console log returns NaN instead of 314.  

I checked your repository tests and found this is the default behaviour but I'm working on a banking project and this way can bring me serious problems.

**Comment by rxaviers** [comment]
#353 needs to be implemented for that. Help very much appreciated. Closing in favor of #353.
