### ISSUE TITLE
unsafe-eval CSP violation in plural.js due to Function constructor

### ISSUE THREAD

**Issue by benlong** [jquery/globalize#591]
Our project is using globalize, and we get a CSP violation for unsafe-eval due to the (new Function) usage in dist/globalize/plural.js (https://github.com/jquery/globalize/blob/1.1.1/dist/globalize/plural.js#L227)

It appears the work around is to add a directive allowing unsafe-eval, which isn't a good idea in most cases since it defeats the purpose of CSP in the first place.

Is this a known issue that is already being addressed? If not, is there a way to put this on the roadmap? Thanks

**Comment by rxaviers** [comment]
The plural module uses [eemeli/make-plural.js](https://github.com/eemeli/make-plural.js) under the hoods. I'm afraid using the `new Function` is the best it can do.

Where do you get the CSP from please? Any conformance entity or your own tools?

**Comment by benlong** [comment]
I don't follow what you mean by conformance entity, but we define our own policies, and our standard is to disallow unsafe-eval.

**Comment by rxaviers** [comment]
Ok, your own policy, got it.

There's a different approach for the plural function that doesn't use `new Function`, but that leads to less efficient runtime code. So, I'm afraid there's no other choice than using this approach here.

/cc @eemeli for his input.

**Comment by eemeli** [comment]
The core `Parser` of make-plural fundamentally requires `new Function` to work, as it's literally compiling a JavaScript function as its output. If you need to not have your live code do that, I'd suggest looking into the precompiled output of make-plural, which [provides](/eemeli/make-plural.js/blob/v3.0.3/plurals.js) the full output of `Parser` when run against CLDR v28.

**Comment by rxaviers** [comment]
Thanks @eemeli.

@benlong the precompiled output of make-plural is provided by Globalize compiler.

**Comment by rxaviers** [comment]
Amended my last comment.

**Comment by rxaviers** [comment]
I'm closing this issue, because there's nothing that can be changed here. Feel free to post new comments if you have any further questions.

**Comment by AirWick219** [comment]
@rxaviers I am running into the same  CSP issue with `new Function` from an app that includes the `dist` in the asset pipeline . Can you elaborate more as to how we can address that in both [message.js](https://github.com/globalizejs/globalize/blob/1.4.2/dist/globalize/message.js) and [plural.js](https://github.com/globalizejs/globalize/blob/1.4.2/dist/globalize/plural.js) without making to monkey patch those calls

**Comment by rxaviers** [comment]
The recommended approach here is to use pre-built formatters (by using globalize-compiler)

**Comment by shansp** [comment]
Hi, can you please show how we can add the precompiled output in plural.js
