### ISSUE TITLE
Doesn't loadMessages stumble on  { } in message value?

### ISSUE THREAD

**Issue by Setogit** [jquery/globalize#592]
query/globalize v1.1.1

loadMessages fails to load a certain message.  Not fully debugged yet, but simply removing { } characters from the message VALUE helps; at least, the message (without { }) is loaded.

Is this a known issue?  I know {} cannot be used in KEY: https://github.com/jquery/globalize/blob/master/doc/api/message/load-messages.md:

JSON object of messages data. Keys can use any character, except /, { and }. Values (i.e., the message content itself) can contain any character.

**Comment by rxaviers** [comment]
`{}` are reserved characters by ICU MessageFormat. Read on [SlexAxton/messageFormatter.js](https://github.com/SlexAxton/messageformat.js/#no-frills) for more information on regard. Anyway, please could you provide examples of what you're trying to load and the error you get?

**Comment by Setogit** [comment]
Got that: "{} are reserved characters of ICU MessageFormat."  Came up with a design B on my side.  closing.

**Comment by rxaviers** [comment]
Ok. Please would you change anything in the docs?
