### ISSUE TITLE
too much complicated setup

### ISSUE THREAD

**Issue by gr3ysky** [jquery/globalize#596]
```
<script src="~/Scripts/globalize.js" type="text/javascript">
</script>
<script src="~/Scripts/globalize.culture.de-DE.js" type="text/javascript">
</script>
<script src="~/Scripts/globalize.culture.en-US.js" type="text/javascript">
</script>
```

This is how much you should need really... 
I really appriciate your work but this way too complicated than it should be.

**Comment by rxaviers** [comment]
You suggested approach might end up adding too much unnecessary byte code to your app.

You can follow your suggestion by using older Globalize 0.x; or for example, by using Andy's Intl.js polyfil, but you start by adding 58.5KB (minified, not gzipped) to your app only for English and only for date formatting and number formatting [[1](https://github.com/andyearnshaw/Intl.js/blob/master/dist/Intl.min.js)] [[2](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/jsonp/en.js)].

By using Globalize, you are able to do the same with an initial 16.6KB (minified, not gzipped) + 1.1KB compiled data (minified, not gzipped). Please, see our provided [example](https://github.com/jquery/globalize/tree/master/examples/app-npm-webpack) and apply [this diff to it](https://gist.github.com/rxaviers/db7d5f25d7a01b01bc54). Run `npm install`, then `npm run build` and you see the result. Globalize grows depending on what your app uses from it (engine wise and data wise).

You may find an easier setup using new Globalize 1.x by using [Globalize with webpack](https://github.com/jquery/globalize/tree/master/examples/app-npm-webpack).

**Comment by rxaviers** [comment]
I hope that helps. We're always open to suggestions to help us improve this library.

**Comment by rxaviers** [comment]
To be clear, I'm closing this ticket, because no actions can be taken to fulfill what you request in your description. Feel free to add new comments in case you have any further questions or suggestions.

**Comment by gr3ysky** [comment]
I found easy to use older version. This version adds too much files. By the way, I use Visual Studio and the npm commands, not working in my current project.
var Globalize = require( "globalize" ); // not working
Anyways thanks for the advice. 
I will still use the older one. No turkish localization is provided yet. But the older one does. And I could do what I wanted with the older one. Thank you again.

**Comment by rxaviers** [comment]
Feel free to use the older version, but note it isn't supported anymore. FWIW, to help you migrate from `0.x` to `1.x` follow a link to our doc plus a blog post:
- https://github.com/jquery/globalize/blob/master/doc/migrating-from-0.x.md
- http://blog.johnnyreilly.com/2015/07/upgrading-to-globalize-1x-for-dummies.html

> No turkish localization is provided yet

This isn't true, Turkish data is available. Use the `tr` locale.

I hope this helps.
