### ISSUE TITLE
E_MISSING_BUNDLE: {"locale":"tr"}

### ISSUE THREAD

**Issue by umutozkn** [jquery/globalize#600]
i cannot use globalize. What is missing :(
`<script src="~/Scripts/cldr.js"></script>
    <script src="~/Scripts/cldr/event.js"></script>
    <script src="~/Scripts/cldr/supplemental.js"></script>
    <script src="~/Scripts/cldr/unresolved.js"></script>
    <script src="~/Scripts/globalize.js"></script>
    <script src="~/Scripts/globalize/message.js"></script>
    <script src="~/Scripts/globalize/number.js"></script>
    <script src="~/Scripts/globalize/plural.js"></script>
    <script src="~/Scripts/globalize/date.js"></script>
    <script src="~/Scripts/globalize/currency.js"></script>
    <script src="~/Scripts/globalize/relative-time.js"></script>
<script>
 $(document).ready(function () {
        Globalize.locale("tr");
    });
</script>`

Error: E_MISSING_CLDR: Missing required CLDR content `supplemental/likelySubtags`.
 globalize.js:105:10
Error: E_MISSING_BUNDLE: {"locale":"tr"}

**Comment by MattWButler** [comment]
Prior to creating any Globalize instance, you must load cldr/supplemental/likelySubtags.json. Read CLDR content if you need more information.
https://github.com/jquery/globalize/blob/ab675203d8784c641c432e3cb10dfce564d80e7a/doc/api/core/constructor.md

http://www.unicode.org/cldr/charts/latest/supplemental/likely_subtags.html


I would recommend checking out the examples.
https://github.com/jquery/globalize/blob/master/examples/plain-javascript/index.html#L204-L206

Good luck!

**Comment by rxaviers** [comment]
Thanks @MattWButler.

@umutozkn, I'm closing the issue. If you have additional questions feel free to include additional comments, in which case I can reopen it.

I also want to point out that documentation improvements are always welcome to help other users get up to speed easier.

**Comment by jeanpoelie** [comment]
A lot of documentation seems to have dissapeared, most references say, see instructions here, and than the readme says: 

> ldr-core
> 
> This repository provides the a portion of the JSON distribution of CLDR locale data for internationalization.
> 
> Refer to the README at https://github.com/unicode-cldr/cldr-json for complete details.

Someone should write a proper instruction for new comers.

**Comment by rxaviers** [comment]
@jeanpoelie please can you list all those places so we can fix them? Thanks
