### ISSUE TITLE
First day of week becomes Saturday only on Sundays, using en-UK locale

### ISSUE THREAD

**Issue by harel** [jquery/globalize#608]
Note: I initially opened a similar ticket in the react-big-calendar repository thinking it might be related to that, but I think its a Globalize issue. 

I'm noticing something very strange going on. 
On Sundays, and only on Sundays, my first day of week becomes Saturday using the en-GB locale. 
Any other day of the week, I get Monday as the first day. This is using the latest Globalize and CLDR data. To test this you'll need to change the computer clock to any given Sunday. I've tested this on a computer in the UK and one in the US (west coast PST).

When ``userlocale`` is a Globalize object loaded with 'en-GB' locale.

```
// On any non Sunday day:
userlocale.formatDate(new Date(), {raw:'e'});
> "2"
```

```
// On a sunday :
userlocale.formatDate(new Date(), {raw:'e'});
> "7"
```

Any ideas?

**Comment by harel** [comment]
Apologies, I missed the purpose of the 'e' format tag - current day. It is a problem in their code i think after all.

**Comment by rxaviers** [comment]
No problem, if you find any problem just let us know. Thanks
