### ISSUE TITLE
Globalize for multiple countries unable to achieve

### ISSUE THREAD

**Issue by jeevajevi** [jquery/globalize#611]
Hi All,

I am using globalize.js for currency formatting. Through this link https://github.com/jquery/globalize/tree/master/examples/plain-javascript i can able to achieve USD. But i need for USD and JPY. Please any one help to solve this issue.

**Comment by rxaviers** [comment]
Closing this issue in favor of http://stackoverflow.com/questions/36788552/currency-formatting-using-globalize-js-for-different-countries instead. Thanks for filing the question there.

**Comment by sompylasar** [comment]
@rxaviers could you please expand the answer with the next steps after CLDR is in place? Thanks.
