### ISSUE TITLE
Globalize consider 9,999.99 in english local (en-CA) valide but not 9 999,99 in french local (fr-CA)

### ISSUE THREAD

**Issue by sguillemette123** [jquery/globalize#613]
Why does the plugin Globalize from jQuery can reconize 9,999.99 in english local (en-CA) but not 9 999,99 in french local (fr-CA). Why is the space causing the problem in this scenario ?

That happen when i call the numberParser method. NaN is returned if i enter 9 999,99 but that should be accepted since the formatter return that. What do you think ?

**Comment by rxaviers** [comment]
Hi @sguillemette123, thanks for reporting this issue. You can find additional information at #292. I'm closing this issue in favor of the latter.

**Comment by rxaviers** [comment]
Summary: parser should loosely match space (32) (what you are trying) vs. no-break space (160) (what the function is expecting).

**Comment by rxaviers** [comment]
Related SO question: http://stackoverflow.com/questions/37059798/why-does-the-jquery-plugin-globalize-reconize-9-999-99-in-english-local-en-ca/37073942
