### ISSUE TITLE
Add script for generating old-style "globalize.culture.xxx.js" cldr-data loader

### ISSUE THREAD

**Issue by sky-code** [jquery/globalize#614]
Migrating guide now not provide any real useful information for fast migration from 0.x
based on this articles 
* http://blog.johnnyreilly.com/2015/07/upgrading-to-globalize-1x-for-dummies.html
* https://medium.com/@skwee357/a-different-approach-for-localizing-react-js-app-d789ea463720#.mkzthmti9

I make script that generate old-style globalize.culture.xxx.js files and then load it as in globalize 0.x 
```javascript
gulp.task('cldr:bundle:supplemental',
    function(cb) {
        var fs = require('fs');

        var cldrPath = './bower_components/cldr-data/';
        var destPath = './wwwroot/lib/globalize-cldr-data/'
        var files = [
            'likelySubtags.json',
            //'currencyData.json', // required for currency
            'numberingSystems.json',
            'timeData.json',
            'weekData.json',
            'plurals.json',
            'ordinals.json'
        ];
        var filesJson = files.map(function(f) {
            return require(cldrPath + 'supplemental/' + f);
        });

        var globalizeLoadJsonString = 'Globalize.load(' +
            filesJson.map(function(json) { return JSON.stringify(json); }).join(', ') +
            ');';

        if (!fs.existsSync(destPath)) {
            fs.mkdirSync(destPath);
        }

        fs.writeFileSync(destPath + 'globalize.supplemental.js', globalizeLoadJsonString);
        cb();
    });

gulp.task('cldr:bundle:locale',
    function(cb) {
        var fs = require('fs');

        var cldrPath = './bower_components/cldr-data/';
        var destPath = './wwwroot/lib/globalize-cldr-data/'

        var files = [
            'ca-gregorian.json',
            'timeZoneNames.json',
            'numbers.json',
            'units.json'
        ];

        if (!fs.existsSync(destPath)) {
            fs.mkdirSync(destPath);
        }

        var locales = fs.readdirSync(cldrPath + 'main');

        locales.map(function(locale) {
            var filesJson = files.map(function(f) {
                return require(cldrPath + 'main/' + locale + '/' + f);
            });

            var globalizeLoadJsonString = 'Globalize.load(' +
                filesJson.map(function(json) { return JSON.stringify(json); }).join(', ') +
                ');';

            fs.writeFileSync(destPath + 'globalize.culture.' + locale + '.js', globalizeLoadJsonString);

        });
        cb();
    });
```
At least now this script solve migration problem for me, but I think will be good to have "official" script in documentation which generate old-style globalize.culture.xxx.js which can be used like in globalize 0.x just by loading it after library itself, it will realy help people with migration
Will be good to have gulp and grunt task scripts writen with comments where all files has comment for what it required, as example:
```javascript
var files = [
            'likelySubtags.json', // required 
            //'currencyData.json', // required for Currency module
            'numberingSystems.json']; // required for Number module
            .. and so on
```

**Comment by rxaviers** [comment]
Hi, thanks for contributing the script.

Globalize 1.x makes use of [CLDR](https://github.com/jquery/globalize/blob/master/doc/cldr.md) as i18n data source, which is available in the JSON format. Therefore, what you are looking for is how to load JSON in a web application. There are numerous ways and it depends on your solution. It seems to me your solution is a gulp plugin for bundling JSON. First, check for a similar existing plugin. Then, we can including this in our documentation as another method for [How do I load CLDR data into Globalize?](https://github.com/jquery/globalize/blob/master/doc/cldr.md#how-do-i-load-cldr-data-into-globalize). Feel free to submit a pull request with the documentation change.

Thanks

**Comment by rxaviers** [comment]
Edit: fixed typos.
