### ISSUE TITLE
Currency formatting without symbols.

### ISSUE THREAD

**Issue by Makac** [jquery/globalize#617]
Hi,

Is there a way to get the currency formatter to omit the currency symbol in its output?

For instance, I'd like Globalize.currencyFormatter( "USD" )( 1 )  to return "1.00" (rather than "$1.00").

Thanks,

Makac

**Comment by rxaviers** [comment]
By using the numberFormatter :), see its maximumFractionDigits and minimumFractionDigits options.

**Comment by cahuja** [comment]
Yup, using the number formatter would have that effect.

**Comment by Makac** [comment]
Yes, it's just that the fractions differ between languages and currencies. E.g for en/USD you get "$1.00" whereas for ja/JPY it's "￥1".

**Comment by rxaviers** [comment]
True. Why do you want it without the symbol? For layout purposes (e.g., different font size / color)?

**Comment by Makac** [comment]
It's for showing wins in a game. It's common that you want to show these without the currency symbol. I'm considering using String.replace and a regexp to strip everything but number and decimal characters from the currency string, but that would be a bit of a hack...

**Comment by rxaviers** [comment]
Ok, the correct is something like the [formatToParts ecma-402 stage 3 proposal](https://github.com/tc39/ecma402/issues/30). I'm open to include any proposal in this line here.

One workaround would indeed be using regexps, inspect the generated formatter `runtimeArgs` for hack help. Try using `{style: "code"}` option to make your workaround easier, the stripping chars are more predictable:

```js
Globalize("en").formatCurrency(1, 'JPY', {style: "code"})
// > '1 JPY'

Globalize("en").formatCurrency(1, 'USD', {style: "code"})
// > '1.00 USD'

```

**Comment by rxaviers** [comment]
the correct solution* (editted)

**Comment by rxaviers** [comment]
Text editted for clarity.
