### ISSUE TITLE
Issue building with webpack

### ISSUE THREAD

**Issue by adamtay82** [jquery/globalize#618]
I'm using react, and webpack and I just can't get the thing to work. I've tried using the webpack globalize plugin, but it also doesn't appear to help

Would very much appreciate any guidance. Here are some of the errors that I'm seeing:

```
WARNING in ./~/cldr-data/DCO.md
Module parse failed: /node_modules/cldr-data/DCO.md Line 1: Unexpected identifier
You may need an appropriate loader to handle this file type.
| If you would like to make a contribution to cldr-data-npm, please certify to the following:
| 
| ---
 @ ./~/cldr-data ^\.\/.*$

WARNING in ./~/cldr-data/LICENSE
Module parse failed: node_modules/cldr-data/LICENSE Line 1: Unexpected identifier
You may need an appropriate loader to handle this file type.
| UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE
| 
|     Unicode Data Files include all data files under the directories
 @ ./~/cldr-data ^\.\/.*$

```

**Comment by MattWButler** [comment]
The warnings indicate that you are importing/requiring a markdown file and the license file. I would check why those files are showing up. 

I struggeld for a bit getting the webpack plugin to work.  The example they provide was very helpful. 
https://github.com/jquery/globalize/tree/master/examples/app-npm-webpack

**Comment by rxaviers** [comment]
Thanks @MattWButler.

@adamtay82, I'm closing this issue. But, feel free to include additional comments if you have further questions, in which case we can reopen the issue.
