### ISSUE TITLE
npm install fails at node install.js

### ISSUE THREAD

**Issue by clazette** [jquery/globalize#633]
Is this a known issue?

Error: connect ECONNREFUSED 192.30.253.112:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
 npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "globalize" "cldr-data"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! cldr-data@29.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cldr-data@29.0.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the cldr-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cldr-data
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls cldr-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Demo\Globalization\packages\npm-debug.log

**Comment by rxaviers** [comment]
Seems like a connection issue. Please, retry and let me know if it still persists.

**Comment by clazette** [comment]
I tried twice before entering the issue just to make sure. I just executed it a third time with the same result. Some of the dependencies are pulled but then it keeps dying on the node install.js command.

**Comment by rxaviers** [comment]
Unfortunately, I cannot reproduce the issue you're experiencing. Although, I'm not running MS Windows. The IP shown in your log (`192.30.253.112:443`) is from github.com, which makes sense. For some reason the connection is failing...

If you have additional information, feel free to post.

**Comment by kborchers** [comment]
Just FYI, I gave this a shot on Windows, Win10 specifically, and the install worked just fine so I would have to agree that this may be some sort of connectivity issue and not an issue with Globalize.

**Comment by clazette** [comment]
Interestingly, some of the files come down and then this error occurs. I think it may be cldr-data that's causing the issue. I, initially, issued the npm install globalize cldr-data command. Which, in retrospect, probably isn't necessary since cldr-data is a globalize dependency. At any rate, I am assuming you guys aren't having an issue with cldr-data either? Since you, likely, already have the files downloaded, is it possible that would cause something different to occur and you wouldn't have the same experience?

I may be grasping. It just seems odd that some of the files would download and then the error occurs. Wouldn't that indicate that it's not a connection issue?

**Comment by rxaviers** [comment]
cldr-data has a post-install hook that fetches CLDR data from several github ZIPs https://github.com/rxaviers/cldr-data-npm/blob/master/urls.json, which is what's failing for you.

I believe a test you can do is downloading these links. We need a reproducible issue.

**Comment by clazette** [comment]
I'll be working on this today. If I encounter something of value, I'll let you know...assuming  you care ;). I'm sure you have your own challenges to solve as well.

**Comment by rxaviers** [comment]
Ok and we definitely care :). As soon as we find anything reproducible, I'll reopen the issue.

**Comment by clazette** [comment]
I, manually, downloaded each of those zip files from the urls.json page without incident. It's worth noting that I am on a corporate PC and we do use a proxy. I have the npm https-proxy and proxy property values set. Initially, I couldn't npm install. It was the configuration of these values that solved that issue. I may have to just attempt this at home although you guys have already validated that it's likely something with my configuration or the corporate network. Thus, this probably isn't going to result in a reproducible issue for you guys. I'll just have to try to work around the issue. Right now, I am just trying to get a handle on all the parts and how to get this to work at all at this point. Thanks for trying...much appreciated.

**Comment by rxaviers** [comment]
Try using `cldr-data-downloader` directly as a (better) test. The usage section at https://github.com/rxaviers/cldr-data-downloader has instructions. Use one of the links from CLDR 29 and use it via JavaScript by running node and typing those commands.

**Comment by clazette** [comment]
I tried the file that's listed in the usage example as well as one of the CDLR 29 links to no avail.

D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\bin>node < my-downloader.js
GET `http://www.unicode.org/Public/cldr/26/json.zip`
D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\lib\download.js:51
      throw error;
      ^

Error: connect ECONNREFUSED 216.97.88.9:80
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\bin>node < my-downloader.js
GET `https://github.com/unicode-cldr/cldr-core/archive/29.0.0.zip`
D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\lib\download.js:51
      throw error;
      ^

Error: connect ECONNREFUSED 192.30.253.113:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by rxaviers** [comment]
Next action items:
 1. I believe we can safely move this issue into https://github.com/rxaviers/cldr-data-downloader, i.e., create a new issue there with the output of your last comment.
 1. Assert it's proxy related. It seems so. The downloader uses request: https://github.com/rxaviers/cldr-data-downloader/blob/master/lib/download.js#L44; https://github.com/request/request;

We're moving away from the scope of Globalize already. So, let's continue the conversation in the to-be-created issue in cldr-data-downloader.

Thanks

**Comment by clazette** [comment]
Agreed, that all makes sense. To be continued...
