### ISSUE TITLE
Is it possible to get locale information?

### ISSUE THREAD

**Issue by systemovich** [jquery/globalize#635]
For example, if I want to obtain the character used for digit grouping to use with another function like autoNumeric.

autoNumeric has a aSep option that is the character to be used for digit grouping. To set the character, I would need to get it from Globalize for the current locale.

**Comment by systemovich** [comment]
var lang = new Cldr(languageId); // e.g. languageId = 'fr';
    var groupingSepararator = lang.get([
        'main', 
        languageId, 
        'numbers', 
        'symbols-numberSystem-latn', 
        'group'
    );

**Comment by rxaviers** [comment]
Also http://stackoverflow.com/questions/32142529/how-to-access-culture-data-in-globalize-js-v1-0-0

**Comment by jzaefferer** [comment]
Maybe add a note about this here? https://github.com/jquery/globalize#where-does-the-data-come-from
