### ISSUE TITLE
Arabic currency changes in cldr 30 cause E_MISSING_CLDR

### ISSUE THREAD

**Issue by nkovacs** [jquery/globalize#640]
In cldr 30, the currencyformat for the arabic number system no longer inherits from the latin ([changeset](http://unicode.org/cldr/trac/changeset/12636/trunk/common/main/root.xml)), so the json data is missing currencySpacing and the accounting format for some arabic locales.

For example, these all fail:

```
var arAE = new Globalize( "ar-AE" );
var arSA = new Globalize( "ar-SA" );

console.log(arAE.formatCurrency(1295, "AED"));
console.log(arAE.formatCurrency(-1295, "AED"));
console.log(arAE.formatCurrency(1295, "AED", { style: "accounting" }));
console.log(arAE.formatCurrency(-1295, "AED", { style: "accounting" }));

console.log(arSA.formatCurrency(1295, "SAR"));
console.log(arSA.formatCurrency(-1295, "SAR"));
console.log(arSA.formatCurrency(1295, "SAR", { style: "accounting" }));
console.log(arSA.formatCurrency(-1295, "SAR", { style: "accounting" }));
```

The webpack example also fails when you try to build production files.

ICU4J and ICU for C fall back to a hard-coded default in this case: http://bugs.icu-project.org/trac/browser/icu4j/trunk/main/classes/core/src/com/ibm/icu/impl/CurrencyData.java#L82

For the missing accounting format, ICU4J falls back to the latin accounting format: http://bugs.icu-project.org/trac/browser/icu4j/trunk/main/classes/core/src/com/ibm/icu/text/NumberFormat.java#L1497
(I couldn't figure out what ICU for C does). 

This StackOverflow question has some more information: http://stackoverflow.com/questions/40056378/bug-hunt-cldr-30-json-data-no-longer-has-currencyspacing-information

**Comment by rxaviers** [comment]
Hi @nkovacs, thanks for the throughout investigation and great description.

It seems this was a bug in CLDR 30.0.0 json, the recent patch release 30.0.2 fixed this issue.
