### ISSUE TITLE
Plain javascript example does not work for me.

### ISSUE THREAD

**Issue by shrzmk** [jquery/globalize#643]
I tried Hello world example with plain javascrpt. It throws Globalize.load is not a function(…) error in console. Please help me get started with this, I'm stuck !!
![image](https://cloud.githubusercontent.com/assets/22978862/19595219/6c674fde-97a6-11e6-8808-fccc7d7be241.png)

**Comment by shrzmk** [comment]
I changed globalize.js file to v1.0.1. The globalise releases site pointed in the document has v0.1.1.  Issue resolved.

**Comment by jzaefferer** [comment]
Where did you find the 0.1.1 reference?

**Comment by shrzmk** [comment]
The 'globalize release tab' in README document pointed me to a site where the latest package was 0.1.1
